import LESSONS from "../lessons.js";

const CATEGORIES = {
  fundamentals: { label: "Rails core & request", color: "#E8A33D" },
  activerecord: { label: "Active Record & DB", color: "#CC342D" },
  patterns: { label: "Diseño aplicado", color: "#5AA9FF" },
  sti: { label: "STI & polimorfismo", color: "#A78BFA" },
  infra: { label: "API, seguridad & runtime", color: "#94A3B8" },
  assets: { label: "Asset pipeline", color: "#2DD4BF" },
  testing: { label: "Testing (RSpec)", color: "#4ADE80" },
};

const NODE_DATA = [
  ["ruby_basics", "Ruby mínimo para leer Rails", "fundamentals"],
  ["mvc", "Rails MVC + convenciones", "fundamentals"],
  ["rack", "Request lifecycle & Rack", "fundamentals"],
  ["routing_rest", "Routing RESTful", "fundamentals"],
  ["controllers_params", "Controllers & strong params", "fundamentals"],
  ["responses_errors", "Responses, status & errores", "fundamentals"],
  ["ar_pattern", "Mental model de Active Record", "activerecord"],
  ["ar_orm", "CRUD, Relation & lazy queries", "activerecord"],
  ["migrations", "Migrations, índices & constraints", "activerecord"],
  ["validations", "Validaciones e integridad", "activerecord"],
  ["assoc_belongs", "belongs_to / has_many", "activerecord"],
  ["transactions", "Transacciones & atomicidad", "activerecord"],
  ["scopes", "Scopes", "activerecord"],
  ["n_plus_one", "N+1 queries", "activerecord"],
  ["eager_loading", "Eager loading", "activerecord"],
  ["assoc_through", "has_many :through", "activerecord"],
  ["service_object", "Service Object", "patterns"],
  ["case_checkout", "Caso: checkout de una orden", "patterns"],
  ["query_object", "Query Object", "patterns"],
  ["case_reporting", "Caso: reporte filtrable", "patterns"],
  ["form_object", "Form Object", "patterns"],
  ["case_signup", "Caso: registro multi-modelo", "patterns"],
  ["callbacks", "Callbacks vs flujo explícito", "patterns"],
  ["jobs_mailers", "Active Job & Mailer", "patterns"],
  ["strategy_pattern", "Strategy Pattern", "patterns"],
  ["adapter_pattern", "Adapter para integraciones", "patterns"],
  ["sti", "Single Table Inheritance", "sti"],
  ["sti_tradeoffs", "Trade-offs de STI", "sti"],
  ["polymorphic", "Polymorphic associations", "sti"],
  ["case_content", "Caso: comentarios reutilizables", "sti"],
  ["api_mode", "Rails API-only + React", "infra"],
  ["serialization_cors", "JSON, serializers & CORS", "infra"],
  ["auth_security", "Auth, autorización & seguridad", "infra"],
  ["react_rails_auth", "Auth React + Rails con tokens", "infra"],
  ["asset_pipeline", "Asset pipeline & fingerprinting", "assets"],
  ["modern_assets", "Webpacker → opciones modernas", "assets"],
  ["rspec_basics", "RSpec: sintaxis & mindset", "testing"],
  ["factory_bot", "FactoryBot", "testing"],
  ["spec_types", "Model, service & request specs", "testing"],
  ["gemfile", "Gemfile & Bundler", "infra"],
  ["env_logger", "Credentials, ENV & logging", "infra"],
];

const PRIORITY_ORDER = [
  "ruby_basics", "mvc", "rack", "routing_rest", "controllers_params", "responses_errors",
  "ar_pattern", "ar_orm", "migrations", "validations", "assoc_belongs", "transactions",
  "scopes", "n_plus_one", "eager_loading", "assoc_through", "service_object", "query_object",
  "case_reporting", "form_object", "strategy_pattern", "adapter_pattern", "jobs_mailers",
  "callbacks", "case_checkout", "case_signup", "sti", "sti_tradeoffs", "polymorphic",
  "case_content", "api_mode", "serialization_cors", "auth_security", "react_rails_auth",
  "asset_pipeline", "modern_assets", "rspec_basics", "factory_bot", "spec_types", "gemfile", "env_logger",
];

const PREREQUISITES = {
  ruby_basics: [], mvc: ["ruby_basics"], rack: ["mvc"], routing_rest: ["rack"],
  controllers_params: ["routing_rest"], responses_errors: ["controllers_params"],
  ar_pattern: ["mvc"], ar_orm: ["ar_pattern"], migrations: ["ar_orm"], validations: ["migrations"],
  assoc_belongs: ["ar_orm"], transactions: ["ar_orm"], scopes: ["ar_orm"], n_plus_one: ["assoc_belongs"],
  eager_loading: ["n_plus_one"], assoc_through: ["assoc_belongs"],
  service_object: ["controllers_params", "transactions"],
  case_checkout: ["service_object", "transactions", "adapter_pattern", "jobs_mailers"],
  query_object: ["scopes"], case_reporting: ["query_object", "eager_loading"],
  form_object: ["service_object", "validations"], case_signup: ["form_object", "transactions", "jobs_mailers"],
  jobs_mailers: ["service_object"], callbacks: ["ar_orm", "jobs_mailers"],
  strategy_pattern: ["service_object"], adapter_pattern: ["service_object"],
  sti: ["assoc_belongs"], sti_tradeoffs: ["sti"], polymorphic: ["assoc_belongs"], case_content: ["polymorphic"],
  api_mode: ["responses_errors", "ar_orm"], serialization_cors: ["api_mode"],
  auth_security: ["controllers_params", "api_mode"], react_rails_auth: ["auth_security", "serialization_cors"],
  asset_pipeline: ["mvc"], modern_assets: ["asset_pipeline"], rspec_basics: ["ar_orm"],
  factory_bot: ["rspec_basics", "migrations"], spec_types: ["rspec_basics", "controllers_params"],
  gemfile: ["ruby_basics"], env_logger: ["gemfile"],
};

const nodes = NODE_DATA.map(([id, label, cat]) => ({
  id,
  label,
  cat,
  lesson: LESSONS[id] ?? null,
  priority: (PRIORITY_ORDER.indexOf(id) + 1) || NODE_DATA.length + 1,
  prerequisites: PREREQUISITES[id] ?? [],
}));

export const RAILS_GRAPH = {
  id: "rails",
  label: "Rails entrevistas",
  title: "Rails interview map",
  subtitle: "Request lifecycle, datos, diseño de negocio, API, seguridad y testing.",
  categories: CATEGORIES,
  nodes,
  edges: Object.entries(PREREQUISITES).flatMap(([target, required]) => required.map((source) => [source, target])),
  milestones: [],
  seniorityBands: [],
};
