import {
  SENIOR_CATEGORIES,
  SENIOR_CATEGORY_CONTEXT,
  SENIOR_DATA,
  SENIOR_PREREQUISITES,
  SENIOR_PRIORITY_ORDER,
  SENIOR_TOPIC_DETAILS,
} from "./seniorReactTopics.js";
import { REACT_AUDIT_NOTES } from "./reactAuditNotes.js";
import { REACT_ADVANCED_AUDIT_NOTES } from "./reactAdvancedAuditNotes.js";
import { REACT_CONCEPTUAL_CORRECTIONS } from "./reactConceptualCorrections.js";
import { REACT_ARCHITECTURE_REVIEW } from "./reactArchitectureReview.js";
import {
  INTERVIEW_EXPANSION_DATA,
  INTERVIEW_EXPANSION_DETAILS,
  INTERVIEW_EXPANSION_PREREQUISITES,
  INTERVIEW_PRIORITY_INSERTIONS,
} from "./reactInterviewExpansion.js";
import {
  GREATFRONTEND_REACT_SOURCE,
  REACT_INTERVIEW_QUESTIONS,
  getInterviewQuestionsForNode,
} from "./reactInterviewQuestions.js";
import { getSupplementalReactSources, REACT_REVIEW_NOTES } from "./reactSources.js";
import { REACT_MILESTONES, REACT_SENIORITY_BANDS } from "./reactMilestones.js";

const makeLesson = (level, summary, why, code, codeLabel, steps, pitfalls, takeaway, extras = {}) => ({
  level,
  summary,
  explanation: extras.explanation ?? null,
  why,
  code: code.replaceAll("\\n", "\n"),
  codeLabel,
  steps,
  pitfalls: pitfalls ?? [],
  takeaway,
  ...extras,
});

const categories = {
  fundamentals: { label: "Modelo mental & componentes", color: "#61DAFB" },
  state: { label: "Estado & datos", color: "#F59E0B" },
  effects: { label: "Efectos & asincronía", color: "#A78BFA" },
  rendering: { label: "Render & performance", color: "#4ADE80" },
  architecture: { label: "Arquitectura web", color: "#2DD4BF" },
  quality: { label: "Testing & calidad", color: "#F472B6" },
  platform: { label: "Web, seguridad & deploy", color: "#94A3B8" },
  designSystem: { label: "Design systems & contratos", color: "#FB7185" },
  ...SENIOR_CATEGORIES,
};

const categoryContext = {
  fundamentals: "Primero construimos el modelo mental que permite predecir cuándo React renderiza y cómo fluyen los datos.",
  state: "Ahora decidimos dónde vive el estado, quién lo modifica y qué datos son fuente de verdad.",
  effects: "Esta rama conecta React con el mundo externo: red, timers, suscripciones y cancelación de trabajo.",
  rendering: "Con el modelo mental claro, optimizamos solo los renders y cálculos que realmente importan.",
  architecture: "Ahora componemos una aplicación completa: rutas, estado de servidor, auth y límites de componentes.",
  quality: "Después de diseñar el comportamiento, aprendemos a probarlo desde la perspectiva del usuario.",
  platform: "Finalmente conectamos React con las reglas reales de la web: accesibilidad, seguridad, SSR y producción.",
  designSystem: "Esta rama avanzada trata componentes reutilizables como productos públicos: protege contratos, comportamiento, accesibilidad, evolución y evidencia.",
  ...SENIOR_CATEGORY_CONTEXT,
};

const data = [
  ["js_basics", "JavaScript moderno para leer React", "fundamentals"],
  ["react_mental_model", "Modelo mental: UI como función del estado", "fundamentals"],
  ["components_props", "Componentes, props y composición", "fundamentals"],
  ["jsx_rendering", "JSX y render declarativo", "fundamentals"],
  ["events_propagation", "Eventos, propagación y acciones del usuario", "fundamentals"],
  ["state_updates", "Estado, snapshots y batching", "state"],
  ["hooks_rules", "Hooks y reglas de uso", "state"],
  ["custom_hooks", "Custom Hooks y composición de lógica", "state"],
  ["use_state_reducer", "useState vs useReducer", "state"],
  ["forms_controlled", "Forms controlados y no controlados", "state"],
  ["form_validation", "Formularios con React Hook Form y schemas", "state"],
  ["lifting_state", "Lifting state y fuente de verdad", "state"],
  ["derived_state", "Estado derivado y normalización", "state"],
  ["context", "Context: alcance y trade-offs", "state"],
  ["refs_dom", "useRef, DOM y valores mutables", "state"],
  ["effects", "useEffect: sincronización externa", "effects"],
  ["effect_dependencies", "Dependencias, cleanup y stale closures", "effects"],
  ["data_fetching", "Data fetching y estados de request", "effects"],
  ["async_race", "Abort, race conditions y retries", "effects"],
  ["routing", "Routing y navegación SPA", "architecture"],
  ["auth_frontend", "Autenticación en React + API", "architecture"],
  ["server_state", "Client state vs server state", "architecture"],
  ["react_query", "TanStack Query y cache de servidor", "architecture"],
  ["optimistic_ui", "Optimistic UI y rollback", "architecture"],
  ["react_actions", "Actions, useActionState y useOptimistic", "architecture"],
  ["render_reconciliation", "Render, reconciliation y commit", "rendering"],
  ["transitions_concurrency", "Transitions, prioridad y UI responsiva", "rendering"],
  ["keys_lists", "Lists, keys y estado preservado", "rendering"],
  ["memoization", "memo, useMemo y useCallback", "rendering"],
  ["react_compiler", "React Compiler y memoización automática", "rendering"],
  ["performance", "Profiling y performance real", "rendering"],
  ["suspense_lazy", "Code splitting, lazy y Suspense", "rendering"],
  ["error_boundaries", "Error boundaries y recuperación", "rendering"],
  ["accessibility", "Accesibilidad como contrato de UI", "platform"],
  ["portals_dialogs", "Portals, modales y gestión de foco", "platform"],
  ["styling_assets", "CSS, assets y diseño de componentes", "platform"],
  ["component_architecture", "Arquitectura de componentes", "architecture"],
  ["component_api_patterns", "Diseño de APIs de componentes", "architecture"],
  ["state_management", "State management: Context, store y URL", "architecture"],
  ["external_stores", "Stores externos y useSyncExternalStore", "architecture"],
  ["typescript_react", "TypeScript aplicado a React", "architecture"],
  ["testing_rtl", "Testing Library y tests de comportamiento", "quality"],
  ["testing_async", "Testing de async, mocks y MSW", "quality"],
  ["security_frontend", "XSS, CSRF, storage y seguridad web", "platform"],
  ["ssr_hydration", "SSR, hidratación y frameworks React", "platform"],
  ["server_components", "Server Components y límites client/server", "platform"],
  ["native_component_contract", "Interop nativa: props, refs y forms", "designSystem"],
  ["public_component_contract", "La superficie pública real de un componente", "designSystem"],
  ["callback_contracts", "Contratos de callbacks y eventos", "designSystem"],
  ["controlled_uncontrolled_api", "APIs controladas y no controladas", "designSystem"],
  ["draft_commit_state", "Draft, commit, cancel y reset", "designSystem"],
  ["library_type_design", "TypeScript para APIs de librería", "designSystem"],
  ["api_evolution", "Evolución, deprecación y migraciones", "designSystem"],
  ["behavior_ownership", "Ownership de comportamiento y paridad nativa", "designSystem"],
  ["accessible_composites", "Patrones accesibles para widgets compuestos", "designSystem"],
  ["design_tokens", "Tokens, theming y hooks de styling", "designSystem"],
  ["resilient_ui", "Layout resiliente, contenido e internacionalización", "designSystem"],
  ["vendor_boundaries", "Fronteras con librerías externas", "designSystem"],
  ["proof_strategy", "Matriz de pruebas para componentes públicos", "designSystem"],
  ["scope_reviewability", "Scope, precedente y reviewability", "designSystem"],
  ["case_design_system_select", "Caso: diseñar un Select reutilizable", "designSystem"],
  ["case_dashboard", "Caso: dashboard con filtros y cache", "architecture"],
  ["case_auth", "Caso: login, rutas protegidas y refresh", "architecture"],
  ["case_checkout", "Caso: checkout React con estados", "architecture"],
  ["deployment_web", "Build, deploy y observabilidad frontend", "platform"],
  ...INTERVIEW_EXPANSION_DATA,
  ...SENIOR_DATA,
];

const priorityOrder = ["js_basics", "react_mental_model", "components_props", "jsx_rendering", "events_propagation", "state_updates", "hooks_rules", "custom_hooks", "use_state_reducer", "forms_controlled", "form_validation", "lifting_state", "derived_state", "context", "refs_dom", "effects", "effect_dependencies", "data_fetching", "async_race", "render_reconciliation", "transitions_concurrency", "keys_lists", "routing", "server_state", "react_query", "optimistic_ui", "react_actions", "auth_frontend", "component_architecture", "component_api_patterns", "state_management", "external_stores", "typescript_react", "memoization", "react_compiler", "performance", "suspense_lazy", "error_boundaries", "accessibility", "portals_dialogs", "styling_assets", "security_frontend", "testing_rtl", "testing_async", "ssr_hydration", "server_components", "native_component_contract", "public_component_contract", "callback_contracts", "controlled_uncontrolled_api", "draft_commit_state", "library_type_design", "api_evolution", "behavior_ownership", "accessible_composites", "design_tokens", "resilient_ui", "vendor_boundaries", "proof_strategy", "scope_reviewability", "case_design_system_select", "case_dashboard", "case_auth", "case_checkout", "deployment_web", ...SENIOR_PRIORITY_ORDER];

INTERVIEW_PRIORITY_INSERTIONS.forEach(({ id, after }) => {
  const currentIndex = priorityOrder.indexOf(id);
  if (currentIndex >= 0) priorityOrder.splice(currentIndex, 1);
  const afterIndex = priorityOrder.indexOf(after);
  priorityOrder.splice(afterIndex >= 0 ? afterIndex + 1 : priorityOrder.length, 0, id);
});

const prerequisites = {
  js_basics: [], react_mental_model: ["js_basics"], components_props: ["react_mental_model"], jsx_rendering: ["components_props"], state_updates: ["components_props"], hooks_rules: ["state_updates"], use_state_reducer: ["hooks_rules"], forms_controlled: ["use_state_reducer"], lifting_state: ["use_state_reducer"], derived_state: ["state_updates"], context: ["lifting_state"], refs_dom: ["hooks_rules"], effects: ["hooks_rules"], effect_dependencies: ["effects"], data_fetching: ["effect_dependencies"], async_race: ["data_fetching"], routing: ["components_props"], auth_frontend: ["routing", "data_fetching"], server_state: ["data_fetching"], react_query: ["server_state"], render_reconciliation: ["react_mental_model", "jsx_rendering"], keys_lists: ["render_reconciliation"], memoization: ["render_reconciliation", "state_updates"], performance: ["memoization", "keys_lists"], suspense_lazy: ["render_reconciliation"], error_boundaries: ["components_props"], accessibility: ["components_props", "jsx_rendering"], styling_assets: ["components_props"], component_architecture: ["components_props", "state_updates"], state_management: ["context", "component_architecture"], typescript_react: ["components_props", "hooks_rules"], testing_rtl: ["components_props", "state_updates"], testing_async: ["testing_rtl", "data_fetching"], security_frontend: ["auth_frontend", "forms_controlled"], ssr_hydration: ["render_reconciliation", "data_fetching"], case_dashboard: ["component_architecture", "react_query", "performance", "testing_async"], case_auth: ["auth_frontend", "security_frontend", "routing"], case_checkout: ["forms_controlled", "server_state", "case_auth"], deployment_web: ["styling_assets", "security_frontend", "performance"],
};

prerequisites.custom_hooks = ["hooks_rules"];
prerequisites.form_validation = ["forms_controlled"];
prerequisites.optimistic_ui = ["react_query", "state_updates"];
prerequisites.transitions_concurrency = ["render_reconciliation", "state_updates"];
prerequisites.react_compiler = ["memoization"];
prerequisites.events_propagation = ["components_props", "jsx_rendering"];
prerequisites.react_actions = ["forms_controlled", "optimistic_ui", "transitions_concurrency"];
prerequisites.component_api_patterns = ["component_architecture", "forms_controlled"];
prerequisites.external_stores = ["state_management", "hooks_rules"];
prerequisites.portals_dialogs = ["events_propagation", "refs_dom", "accessibility"];
prerequisites.server_components = ["ssr_hydration", "suspense_lazy"];
Object.assign(prerequisites, SENIOR_PREREQUISITES);
Object.assign(prerequisites, INTERVIEW_EXPANSION_PREREQUISITES);
prerequisites.native_component_contract = ["components_props", "forms_controlled", "refs_dom", "typescript_react"];
prerequisites.public_component_contract = ["component_api_patterns", "native_component_contract"];
prerequisites.callback_contracts = ["events_propagation", "public_component_contract"];
prerequisites.controlled_uncontrolled_api = ["forms_controlled", "lifting_state", "public_component_contract"];
prerequisites.draft_commit_state = ["use_state_reducer", "controlled_uncontrolled_api"];
prerequisites.library_type_design = ["typescript_react", "public_component_contract"];
prerequisites.api_evolution = ["library_type_design", "public_component_contract"];
prerequisites.behavior_ownership = ["native_component_contract", "draft_commit_state", "component_architecture"];
prerequisites.accessible_composites = ["accessibility", "events_propagation", "portals_dialogs", "public_component_contract"];
prerequisites.design_tokens = ["styling_assets", "public_component_contract"];
prerequisites.resilient_ui = ["accessibility", "design_tokens"];
prerequisites.vendor_boundaries = ["component_architecture", "library_type_design"];
prerequisites.proof_strategy = ["testing_rtl", "testing_async", "accessible_composites", "design_tokens"];
prerequisites.scope_reviewability = ["api_evolution", "behavior_ownership", "vendor_boundaries", "proof_strategy"];
prerequisites.case_design_system_select = ["callback_contracts", "draft_commit_state", "api_evolution", "behavior_ownership", "accessible_composites", "resilient_ui", "proof_strategy"];
prerequisites.case_dashboard = ["component_architecture", "routing", "react_query", "performance", "testing_async"];
prerequisites.case_auth = ["auth_frontend", "security_frontend", "routing", "async_race"];
prerequisites.case_checkout = ["form_validation", "async_race", "optimistic_ui", "case_auth"];

const commonPitfalls = null;
const commonSteps = ["Identificá la fuente de verdad y quién posee la decisión.", "Modelá estados de loading, éxito, error y recuperación cuando haya trabajo externo.", "Elegí una frontera pequeña que pueda probarse y cambiar sin arrastrar toda la app."];

const topicDetails = {
  js_basics: ["Base", "JavaScript moderno aporta closures, módulos, Promises e inmutabilidad; muchos bugs de React son bugs de referencias o asincronía.", "Necesitás leer la sintaxis que aparece en hooks, handlers y data fetching.", "const add = (items, item) => [...items, item]\\n\\nasync function load() {\\n  const response = await fetch(\"/api/items\")\\n  return response.json()\\n}", "Closures, módulos y Promises", ["Una closure conserva variables de su scope aunque la función se ejecute después.", "Una Promise representa trabajo futuro; async/await no lo convierte en síncrono.", "La inmutabilidad crea una nueva referencia para que las comparaciones detecten cambios."], ["Mutar arrays/objetos existentes puede ocultar cambios.", "No confundas una referencia nueva con datos necesariamente nuevos."], "Para leer React: dominá closures, módulos, Promises y copias inmutables."],
  react_mental_model: ["Fundamento", "React calcula una descripción de UI a partir de props, state y contexto; luego compara y aplica cambios durante el commit.", "Este modelo explica renders, effects, memoización y por qué no se manipula el DOM manualmente para cada cambio.", "function Counter() {\\n  const [count, setCount] = useState(0)\\n  return <button onClick={() => setCount(count + 1)}>{count}</button>\\n}", "Estado → render → commit", ["Renderizar calcula una descripción y no implica que todo el DOM cambie.", "El render debe ser puro porque React puede repetirlo.", "Los effects sincronizan sistemas externos después del commit."], ["No hagas fetch ni mutaciones globales durante render.", "setState agenda otro render; no es una asignación inmediata común."], "Render = calcular UI; commit = aplicarla; effect = sincronizar lo externo."],
  components_props: ["Fundamento", "Los componentes son funciones que reciben props y componen UI mediante contratos pequeños.", "La composición escala mejor que herencias y componentes universales.", "function Card({ title, children }) {\\n  return <section><h2>{title}</h2>{children}</section>\\n}\\n\\n<Card title=\"Orders\"><OrdersTable /></Card>", "Composición y children", ["Props son entradas de solo lectura.", "children permite inyectar contenido sin que el contenedor conozca sus detalles.", "Callbacks permiten pedir cambios al dueño del estado."], commonPitfalls, "Componé piezas con contratos pequeños y ownership claro."],
  jsx_rendering: ["Fundamento", "JSX describe elementos y expresiones JavaScript; no es HTML que se inserta línea por línea.", "Evita errores con listas, expresiones, semántica y contenido no confiable.", "const active = true\\nreturn <article>{active && <Badge>Active</Badge>}</article>", "JSX como descripción", ["Las llaves evalúan expresiones JavaScript.", "React escapa texto por defecto; dangerouslySetInnerHTML necesita sanitización.", "Las listas se construyen con map y keys estables."], commonPitfalls, "JSX describe la UI y React decide cómo actualizarla."],
  state_updates: ["Estado", "State es un snapshot del render actual; actualizarlo agenda otro render y React puede agrupar actualizaciones.", "Explica por qué dos setters que usan el mismo valor viejo no necesariamente se acumulan.", "setCount(value => value + 1)\\nsetCount(value => value + 1)", "Actualización funcional", ["Cuando el siguiente valor depende del anterior, usá la forma funcional.", "En objetos y arrays creá nuevas referencias.", "Leer state después del setter dentro del mismo handler devuelve el snapshot anterior."], commonPitfalls, "State no es una variable mutable común: alimenta el próximo render."],
  hooks_rules: ["Hooks", "Los Hooks permiten estado y capacidades de React en funciones, pero su orden de llamadas debe ser estable.", "Las reglas permiten que React asocie cada Hook con el mismo estado en cada render.", "function Search({ enabled }) {\\n  const [term, setTerm] = useState(\"\")\\n  useEffect(() => { if (!enabled) return }, [enabled, term])\\n}", "Reglas de Hooks", ["Llamá Hooks en el nivel superior o dentro de custom Hooks.", "No los llames dentro de if, loops o funciones anidadas.", "Un custom Hook comparte lógica, pero cada llamada tiene su propio estado."], commonPitfalls, "El orden estable de Hooks es un contrato con React."],
  use_state_reducer: ["Estado", "useState sirve para estado local simple; useReducer expresa transiciones relacionadas mediante eventos.", "Elegirlo bien evita setters dispersos o reducers innecesarios.", "function reducer(state, action) {\\n  if (action.type === \"added\") return { ...state, items: [...state.items, action.item] }\\n  return state\\n}", "Estado por eventos", ["useState es claro para transiciones pequeñas.", "useReducer concentra reglas en una función pura.", "El reducer no llama APIs ni muta state."], commonPitfalls, "useState describe valores; useReducer describe transiciones."],
  forms_controlled: ["Estado", "Un input controlado recibe value desde React y notifica cambios; uno no controlado conserva el valor en el DOM y se lee con ref.", "La elección afecta validación, rendimiento e integración con librerías.", "<input value={email} onChange={event => setEmail(event.target.value)} />", "Formulario controlado", ["El state es la fuente de verdad del valor controlado.", "Submit debe modelar validación, submitting, éxito y error.", "Un formulario grande puede usar inputs no controlados para reducir renders, sin perder un contrato de validación."], commonPitfalls, "Controlado = React conoce el valor; no controlado = el DOM lo conserva."],
  lifting_state: ["Estado", "Lifting state mueve el estado al ancestro común cuando varios componentes necesitan la misma fuente de verdad.", "Evita copias divergentes de un filtro, selección o draft compartido.", "function Orders() {\\n  const [status, setStatus] = useState(\"all\")\\n  return <><StatusSelect value={status} onChange={setStatus} /><OrdersTable status={status} /></>\\n}", "Una fuente de verdad", ["El padre pasa value y callbacks.", "El hijo no duplica la misma fuente de verdad.", "Si la distancia crece, evaluá Context, URL o un store."], commonPitfalls, "Una fuente de verdad reduce estados imposibles."],
  derived_state: ["Estado", "Si un valor puede calcularse a partir de props o state existente, normalmente no debe guardarse como state adicional.", "Evita duplicados desincronizados como filteredItems junto a items y query.", "const filtered = items.filter(item => item.name.includes(query))", "Calcular en render", ["Guardá la mínima fuente de verdad.", "Calculá valores derivados durante render si el costo es razonable.", "Usá useMemo solo si el cálculo es costoso y medido."], commonPitfalls, "Guardá fuentes de verdad; derivá el resto."],
  context: ["Estado", "Context entrega un valor a muchos descendientes sin pasar props por cada nivel, pero no es automáticamente un store eficiente.", "Sirve para tema, idioma o usuario actual; puede ocultar dependencias y propagar renders.", "const ThemeContext = createContext(\"light\")\\nconst theme = useContext(ThemeContext)", "Alcance de una dependencia", ["El Provider define el valor para un subárbol.", "El consumidor se actualiza cuando cambia el value.", "Separá contexts por responsabilidad y frecuencia de cambio."], commonPitfalls, "Context resuelve alcance; no reemplaza cache de servidor ni cualquier store."],
  refs_dom: ["Hooks", "useRef conserva un valor mutable entre renders sin provocar render y puede apuntar a un nodo DOM.", "Sirve para focus, timers, valores previos e integraciones imperativas.", "const inputRef = useRef(null)\\n<input ref={inputRef} />\\ninputRef.current.focus()", "Referencia al DOM", ["ref.current se asigna después del commit.", "Cambiar ref.current no actualiza UI.", "Para datos visibles usá state; para un recurso mutable usá ref."], commonPitfalls, "State actualiza UI; ref conserva una referencia sin pedir UI nueva."],
  effects: ["Efectos", "useEffect sincroniza React con sistemas externos después del commit: red, timers, suscripciones o APIs del browser.", "Muchos bugs vienen de usar effects para cálculos o eventos que no son sincronización externa.", "useEffect(() => {\\n  const connection = createConnection(roomId)\\n  connection.connect()\\n  return () => connection.disconnect()\\n}, [roomId])", "Sincronización externa", ["El effect corre después del commit.", "Cleanup deshace la sincronización anterior.", "Las dependencias describen valores externos usados por el effect."], commonPitfalls, "Un effect debe responder qué sincroniza, de qué depende y cómo se limpia."],
  effect_dependencies: ["Efectos", "Dependencias y cleanup determinan qué closure observa el effect y cuándo se cancela el trabajo anterior.", "Es la base para evitar stale closures, listeners duplicados y respuestas viejas.", "useEffect(() => {\\n  let ignore = false\\n  api.get(userId).then(data => { if (!ignore) setUser(data) })\\n  return () => { ignore = true }\\n}, [userId])", "Closure y cleanup", ["Cada render crea una closure con sus valores.", "Omitir dependencias puede dejar el effect leyendo un valor viejo.", "AbortController puede cancelar una request."], commonPitfalls, "Cada effect necesita dependencias completas y una estrategia de cleanup."],
  data_fetching: ["Asincronía", "Fetch real necesita modelar loading, success, error, retry y qué pasa si la pantalla cambia antes de terminar.", "La request feliz es fácil; la calidad aparece en estados incompletos y errores.", "const controller = new AbortController()\\nfetch(\"/api/users\", { signal: controller.signal })\\nreturn () => controller.abort()", "Estados de una request", ["Definí idle/loading/success/error.", "Tratà statuses HTTP no exitosos como errores.", "Separá cache, retry y deduplicación cuando el problema crece."], commonPitfalls, "Data fetching es estado, concurrencia y cache, no solo fetch."],
  async_race: ["Asincronía", "Una race condition ocurre cuando respuestas fuera de orden actualizan state con una selección ya vieja.", "Es común en búsquedas, autocompletes, filtros y navegación rápida.", "const id = ++latestRequest\\nconst result = await search(query)\\nif (id === latestRequest) setResults(result)", "Solo la respuesta vigente gana", ["Dos requests pueden terminar en orden distinto al de inicio.", "Usá AbortController y/o un request id.", "Retry necesita backoff, cancelación y límite."], commonPitfalls, "La UI debe decidir qué respuesta sigue vigente."],
  routing: ["Arquitectura", "El router relaciona URL con pantalla y parámetros; una SPA cambia la pantalla sin recargar el documento.", "Routing define URLs compartibles, historial, deep links, loading de rutas y auth.", "<Route path=\"/orders/:id\" element={<OrderDetail />} />", "URL como estado navegable", ["Params de ruta identifican recursos.", "Query params suelen representar filtros y paginación.", "Ocultar una ruta no autoriza datos en el backend."], commonPitfalls, "Routing es contrato entre URL, pantalla, historial y permisos."],
  auth_frontend: ["Arquitectura", "React coordina login, access token, refresh, logout y estados de sesión, pero la API sigue siendo autoridad de identidad y permisos.", "Es un flujo popular en entrevistas fullstack y tiene errores sutiles con 401, refresh y retries.", "fetch(API_URL + \"/orders\", { headers: { Authorization: \"Bearer <access-token>\" } })", "Cliente API", ["Login obtiene credenciales y tokens por HTTPS.", "401 puede disparar refresh una sola vez y reintentar.", "401 no es igual a 403: el primero es identidad ausente/inválida; el segundo es permiso insuficiente.", "Logout limpia cache sensible y revoca el refresh cuando el backend lo permite."], commonPitfalls, "React coordina la experiencia de sesión; la API autoriza cada request."],
  server_state: ["Arquitectura", "Server state pertenece al backend y puede cambiar fuera de tu componente; client state representa interacción local o intención del usuario.", "Separarlos evita usar Context o Redux como cache manual de datos remotos.", "const [isOpen, setOpen] = useState(false)\\nconst orders = useOrdersQuery(filters)", "Dos ciclos de vida", ["Modal y draft son client state.", "Orders y profile son server state con freshness e invalidación.", "La herramienta debe seguir el ciclo de vida del dato."], commonPitfalls, "Preguntá quién posee el dato, quién lo modifica y cuánto puede quedar viejo."],
  react_query: ["Arquitectura", "TanStack Query encapsula cache, deduplicación, loading, error, retry e invalidación de datos de servidor.", "Es una solución popular para no repetir estado async en cada componente.", "useQuery({ queryKey: [\"orders\", filters], queryFn: () => api.orders(filters) })", "Cache declarativa", ["queryKey identifica el dato cacheado.", "queryFn lo obtiene.", "Una mutación debe invalidar o actualizar las queries afectadas.", "Optimistic updates necesitan rollback si falla."], commonPitfalls, "La cache necesita identidad, freshness e invalidación explícitas."],
  render_reconciliation: ["Render", "React puede renderizar para calcular UI, reconciliar árboles y hacer commit de cambios al DOM.", "Distinguir render de commit permite entender effects, keys y performance.", "function App({ theme }) {\\n  const label = theme === \"dark\" ? \"Dark\" : \"Light\"\\n  return <Toolbar label={label} />\\n}", "Render no es manipular DOM", ["El render debe ser puro.", "Un render no implica que todos los nodos DOM cambien.", "Profiler muestra costo real de renders y commits."], commonPitfalls, "React calcula primero y aplica después."],
  keys_lists: ["Render", "Una key identifica la identidad de un elemento de una lista y determina qué estado local se conserva.", "No es solo un warning: define cómo React relaciona elementos viejos y nuevos.", "items.map(item => <Row key={item.id} item={item} />)", "Identidad estable", ["Usá ids estables del dominio.", "El índice falla cuando se insertan o reordenan elementos.", "Cambiar una key a propósito puede resetear un subárbol."], commonPitfalls, "Keys modelan identidad, y la identidad determina qué estado sobrevive."],
  memoization: ["Performance", "memo, useMemo y useCallback pueden evitar trabajo repetido, pero son optimizaciones que necesitan evidencia.", "Memoizar todo agrega comparaciones, memoria, dependencias y complejidad; solo conviene cuando el trabajo evitado cuesta más que mantener y comparar el valor cacheado.", "const Row = memo(RowComponent)\\nconst visible = useMemo(() => filter(items, query), [items, query])", "Optimización medida", ["Medí primero con Profiler.", "memo sirve si props estables y render costoso justifican comparar.", "useCallback sirve si la identidad estable evita trabajo real."], commonPitfalls, "Optimización = medición y trade-off, no decorar componentes."],
  performance: ["Performance", "Performance frontend incluye JS, renders, layout/paint, red, imágenes y bundle; React es solo una parte.", "Una entrevista senior espera diagnóstico, no una lista de memoizaciones.", "Medí con React DevTools Profiler y Performance panel.\\nPreguntá: ¿qué interacción está lenta y dónde se gasta el tiempo?", "Diagnóstico", ["Reproducí y medí.", "Elegí virtualización, paginación, debounce, code splitting o memo según la causa.", "Medí después del cambio."], commonPitfalls, "Encontrá el cuello de botella real antes de optimizar."],
  suspense_lazy: ["Render", "lazy divide código por feature y Suspense muestra fallback mientras carga una dependencia suspendida.", "Reduce bundle inicial, pero introduce estados de loading que deben tener buena UX.", "const Reports = lazy(() => import(\"./Reports\"))\\n<Suspense fallback={<Skeleton />}><Reports /></Suspense>", "Carga diferida", ["Dividí por rutas o features reales.", "Diseñá fallback que reserve espacio.", "Code Suspense y data Suspense no son exactamente lo mismo."], commonPitfalls, "Code splitting cambia cuándo llega el código; diseñá ese loading."],
  error_boundaries: ["Render", "Un Error Boundary captura errores durante render en un subárbol y permite recuperación localizada.", "Evita que un widget roto derribe toda la aplicación y permite que cada zona ofrezca una recuperación acorde, sin convertir un fallo local en una pantalla completamente inutilizable.", "class Boundary extends React.Component {\\n  static getDerivedStateFromError() { return { hasError: true } }\\n}", "Frontera de fallo", ["Aislá widgets o rutas independientes.", "Registrá el error con contexto.", "Fetch y event handlers necesitan manejo explícito: no todos los errores llegan al boundary."], commonPitfalls, "Los errores también tienen límites de arquitectura."],
  accessibility: ["Web", "Accesibilidad permite usar la UI con teclado, lector de pantalla, contraste y distintos modos de interacción.", "Amplía quién puede completar el flujo y obliga a expresar semántica, foco y feedback de forma verificable; esos mismos contratos también producen una UI más robusta y tests más útiles.", "<button aria-label=\"Close dialog\" onClick={onClose}>×</button>", "Semántica y foco", ["Usá HTML semántico.", "Todo control debe tener nombre y foco accesible.", "Un modal debe gestionar foco, Escape y retorno del foco."], commonPitfalls, "Accesibilidad es comportamiento funcional, no decoración posterior."],
  styling_assets: ["Web", "CSS y assets forman parte del contrato: layout, estados, responsive, fuentes, imágenes y focus deben ser predecibles.", "Una UI profesional cubre loading/error/responsive, no solo el happy path.", "<button className={loading ? \"button is-loading\" : \"button\"}>{loading ? <Spinner /> : children}</button>", "Estados visuales", ["Definí variantes consistentes.", "Reservá espacio para evitar layout shift.", "Optimizar imágenes y fuentes puede superar microoptimizaciones de React."], commonPitfalls, "Calidad frontend incluye estados, semántica y rendimiento visual."],
  component_architecture: ["Arquitectura", "Una feature React sana separa composición, hooks de coordinación, UI y acceso a datos sin crear capas por reflejo.", "Permite crecer sin que cada componente conozca router, API, store y dominio completo.", "function OrdersPage() { const filters = useOrdersFilters(); const orders = useOrdersQuery(filters.value); return <OrdersScreen filters={filters} orders={orders} /> }", "Frontera de feature", ["Organizá por capacidad de negocio.", "Hooks encapsulan coordinación; componentes presentacionales reciben contratos simples.", "El acceso a API debe tener una frontera testeable."], commonPitfalls, "Buena arquitectura hace visible quién posee datos, eventos, UI y efectos."],
  state_management: ["Arquitectura", "El estado puede vivir en componente, URL, Context, store externo o cache de servidor según alcance, frecuencia y ownership.", "Evita tanto prop drilling accidental como meter todo en un store global.", "URL: filtros compartibles\\nContext: tema\\nStore: carrito\\nQuery cache: órdenes", "Elegir dueño", ["Local state es para interacción aislada.", "URL es para filtros y navegación compartibles.", "Context es para dependencias de alcance amplio.", "Store es para client state complejo compartido.", "Query cache es para datos remotos."], commonPitfalls, "La pregunta no es qué librería está de moda: es quién posee el dato."],
  typescript_react: ["Arquitectura", "TypeScript hace explícitos contratos de props, eventos y respuestas, pero no valida datos externos en runtime.", "Una entrevista compleja evalúa si distinguís seguridad estática de datos reales de red.", "type Order = { id: string; status: \"pending\" | \"paid\" }\\ntype Props = { order: Order; onCancel: (id: string) => void }", "Contratos y unions", ["Tipá props y callbacks en el borde.", "Usá unions discriminadas para estados excluyentes.", "Parseá JSON externo con schema si necesitás garantía runtime."], commonPitfalls, "TypeScript verifica desarrollo; datos externos requieren validación runtime."],
  testing_rtl: ["Testing", "React Testing Library prueba lo que el usuario puede observar y hacer, no la implementación interna.", "Los tests de comportamiento sobreviven mejor a refactors porque protegen el contrato visible —qué encuentra, hace y recibe la persona— en vez de acoplarse a funciones o estado internos.", "render(<LoginForm onSubmit={submit} />)\\nawait user.click(screen.getByRole(\"button\", { name: /sign in/i }))\\nexpect(submit).toHaveBeenCalled()", "Interacción observable", ["Buscá por role, label o texto.", "Usá user-event para interacción realista.", "Mockeá la frontera externa, no cada función interna."], commonPitfalls, "Probá intención del usuario y resultado observable."],
  testing_async: ["Testing", "Los tests async deben controlar requests, loading, éxito, error y cleanup sin depender de una red real.", "La asincronía genera flakiness y falsas garantías si se testea mal.", "server.use(http.get(\"/api/orders\", () => HttpResponse.json([{ id: \"1\" }])))\\nexpect(await screen.findByText(/1/)).toBeInTheDocument()", "Mockear servidor con MSW", ["MSW intercepta requests como una API real.", "Usá findBy/waitFor, no sleeps.", "Probá error, timeout, retry y respuesta vacía si son parte del contrato."], commonPitfalls, "Mockeá el servidor y probá la UI que reacciona a la red."],
  security_frontend: ["Seguridad", "React escapa texto por defecto, pero XSS, CSRF, tokens, URLs y datos externos requieren decisiones explícitas.", "La seguridad se rompe en los bordes: HTML crudo, storage, redirects y confianza en el cliente.", "return <p>{comment.body}</p>\\n\\n// dangerouslySetInnerHTML solo con HTML sanitizado", "Fronteras de confianza", ["El backend valida y autoriza; React mejora UX.", "Sanitizá HTML si realmente lo necesitás.", "Evaluá access token en memoria y refresh HttpOnly frente a localStorage.", "Todo incluido en el bundle es público."], commonPitfalls, "El cliente nunca es la autoridad final."],
  ssr_hydration: ["Web", "SSR envía HTML del servidor y la hidratación conecta ese HTML con React para volverlo interactivo.", "Permite razonar sobre contenido visible antes del JavaScript, SEO, primera carga y hydration mismatches, además de entender qué responsabilidad asumen frameworks como Next.", "// Server: HTML inicial\\n// Client: hidrata y conecta handlers", "HTML primero, interactividad después", ["SSR puede mejorar primera respuesta pero agrega complejidad.", "Hydration mismatch aparece si server y primer render client difieren.", "window/localStorage no existen durante render server."], commonPitfalls, "SSR cambia dónde se calcula el primer render; hydration exige markup compatible."],
  case_dashboard: ["Caso de arquitectura", "Un dashboard combina filtros en URL, query cache, tablas grandes, estados de loading/error y widgets independientes.", "Es una consigna popular porque prueba estado, performance, composición y UX real.", "const filters = useUrlFilters()\\nconst orders = useQuery({ queryKey: [\"orders\", filters], queryFn: () => api.orders(filters) })", "Dashboard completo", ["URL es fuente de verdad para filtros compartibles.", "Query cache maneja freshness e invalidación.", "Cada widget puede tener loading/error propio.", "Una lista grande necesita paginación o virtualización."], commonPitfalls, "URL para filtros, query cache para server state y límites por widget.", { prompt: "Diseñá un dashboard con filtros, tabla paginada y widgets que no se bloqueen entre sí." }],
  case_auth: ["Caso de arquitectura", "Auth frontend combina bootstrap de sesión, rutas protegidas, refresh, logout y permisos visibles.", "Revela si entendés autenticación versus autorización y estados de carga.", "if (status === \"loading\") return <Skeleton />\\nif (!user) return <Navigate to=\"/login\" />\\nreturn <AccountPage />", "Ruta protegida", ["No redirijas mientras auth está loading.", "401 puede refrescar; 403 significa permiso insuficiente.", "Logout debe limpiar cache sensible y revocar sesión cuando se pueda.", "El backend autoriza cada request."], commonPitfalls, "Frontend organiza sesión; backend decide la verdad.", { prompt: "Diseñá login, ruta protegida, refresh token y manejo de 401 sin loops." }],
  case_checkout: ["Caso de arquitectura", "Checkout frontend es una máquina de estados que coordina formulario, validación, request, doble submit y resultado de pago.", "Una consigna real evalúa estados ambiguos, retries y consistencia con el backend.", "if (status === \"submitting\") return\\nsetStatus(\"submitting\")\\nconst order = await api.createOrder({ ...data, idempotencyKey })", "Submit idempotente", ["El frontend valida UX; el backend sigue siendo autoridad.", "Deshabilitá/deduplicá submit durante la request.", "Diferenciá validación, rechazo, timeout y pending.", "No limpies carrito antes de confirmar resultado durable."], commonPitfalls, "El frontend expresa estados; el backend define el estado real de la orden.", { prompt: "Diseñá checkout React tolerante a doble click, timeout, pago pendiente y retry." }],
  deployment_web: ["Producción", "El build transforma módulos y assets en archivos públicos; producción agrega cache, variables, observabilidad y deploy reproducible.", "Una entrevista fullstack puede preguntar qué ocurre entre un commit y una UI desplegada.", "src -> bundle/chunks fingerprinted -> CDN -> browser -> Rails API", "De source a producción", ["Variables del frontend son públicas; no pongas secretos en el bundle.", "Configurá fallback de rutas SPA y cache de assets fingerprinted.", "CI ejecuta lint, types, tests y build.", "Monitoreá errores y Web Vitals con releases identificables."], commonPitfalls, "Un frontend profesional también tiene build, cache, observabilidad y contrato de deploy.", { mermaid: "flowchart LR\n A[Commit] --> B[CI]\n B --> C[Build]\n C --> D[CDN]\n D --> E[React]\n E --> F[Rails API]", diagramTitle: "Pipeline frontend" }],
};

topicDetails.custom_hooks = ["Hooks", "Un custom Hook encapsula lógica reutilizable de estado, effects o suscripciones sin reutilizar markup.", "Evita duplicar coordinación en componentes y permite testear la lógica con una frontera clara.", "function useOnlineStatus() {\\n  const [online, setOnline] = useState(navigator.onLine)\\n  useEffect(() => { /* subscribe */ }, [])\\n  return online\\n}", "Lógica reutilizable", ["Un custom Hook comparte comportamiento, no una instancia global de state.", "Su API debe exponer datos y acciones del dominio, no detalles accidentales de la UI.", "Si dos hooks necesitan sincronizar un mismo recurso global, evaluá un store externo."], commonPitfalls, "Extraé un custom Hook cuando el comportamiento se repite y tiene una frontera con nombre."];
topicDetails.form_validation = ["Estado", "React Hook Form y schemas como Zod separan registro eficiente de inputs y validación declarativa de datos.", "Es una solución popular para formularios grandes, pero el schema del cliente no reemplaza la validación del backend.", "const schema = z.object({ email: z.string().email(), age: z.number().int() })\\nconst { register, handleSubmit, formState } = useForm({ resolver: zodResolver(schema) })", "Form library + schema", ["El schema valida forma y mensajes en el cliente.", "El backend vuelve a validar porque el cliente es manipulable.", "Mapeá errores del backend a campos y errores generales.", "Elegí controlled/uncontrolled según costo de renders y necesidades de UI."], commonPitfalls, "Una librería reduce plumbing; la regla de negocio sigue siendo del servidor."];
topicDetails.optimistic_ui = ["Arquitectura", "Optimistic UI actualiza la pantalla antes de la respuesta del servidor y revierte si la operación falla.", "Hace que una interacción se sienta instantánea, pero exige rollback y una estrategia para respuestas concurrentes.", "onMutate: async item => {\\n  await cancelQueries()\\n  const previous = cache.get()\\n  cache.set([...previous, item])\\n  return { previous }\\n}\\nonError: (_error, _item, context) => cache.set(context.previous)", "Actualización optimista", ["Guardá snapshot previo antes de mutar cache.", "Confirmá o reconciliá con la respuesta real del backend.", "Rollback ante error y comunicá el motivo.", "No uses optimistic update si el resultado tiene efectos irreversibles o incertidumbre alta."], commonPitfalls, "Optimistic UI es una predicción controlada, no una confirmación falsa."];
topicDetails.transitions_concurrency = ["Render", "startTransition marca una actualización no urgente para que una interacción urgente como escribir conserve respuesta.", "Ayuda con filtros o navegación costosa, pero no hace más rápida la API ni cancela trabajo por sí sola.", "const [isPending, startTransition] = useTransition()\\nfunction onChange(value) {\\n  setInput(value)\\n  startTransition(() => setFilter(value))\\n}", "Prioridad de actualización", ["Separá el state urgente del trabajo derivado costoso.", "Mostrá isPending si la transición necesita feedback.", "La transición no reemplaza debounce/cancelación de requests.", "El render concurrente exige que render sea puro y efectos tengan cleanup."], commonPitfalls, "Transitions priorizan experiencia; no son una solución genérica de performance."];
topicDetails.react_compiler = ["Performance", "React Compiler puede automatizar algunas optimizaciones de memoización a partir del análisis del código, pero no elimina la necesidad de componentes puros y contratos claros.", "Una entrevista actual puede preguntar qué optimizarías manualmente y qué dejarías al tooling.", "// Código normal y puro\\nfunction Row({ item }) {\\n  return <span>{item.name}</span>\\n}\\n\\n// El compiler puede evitar trabajo repetido cuando puede demostrar seguridad.", "Tooling versus memo manual", ["La pureza permite que tooling y React razonen sobre el componente.", "Memo manual sigue existiendo cuando necesitás expresar una frontera específica.", "No uses efectos o mutaciones ocultas esperando que el compiler las haga seguras.", "Medí el resultado: menos código de optimización no garantiza menos trabajo."], commonPitfalls, "El compiler reduce boilerplate de optimización; no reemplaza el modelo mental ni la medición."];

topicDetails.events_propagation = ["Fundamento", "Un evento empieza en un elemento del navegador y React ejecuta los handlers declarados en el árbol de componentes; normalmente el evento burbujea desde el objetivo hacia sus ancestros.", "Es la base para formularios, delegación, modales y componentes compuestos, y evita confundir una acción del usuario con un Effect.", "function SearchForm() {\\n  function submit(event) {\\n    event.preventDefault()\\n    runSearch(new FormData(event.currentTarget))\\n  }\\n  return <form onSubmit={submit}><button>Buscar</button></form>\\n}", "Evento → handler → actualización", ["React recibe una función en onClick u onSubmit; no debés ejecutarla durante render.", "event.target es el nodo donde nació el evento y event.currentTarget es el nodo cuyo handler está corriendo.", "preventDefault evita la acción predeterminada, como recargar al enviar un form; stopPropagation evita que el evento siga hacia ancestros.", "El handler expresa una acción puntual. useEffect se reserva para sincronización causada por haber renderizado."], ["Pasar onClick={save()} ejecuta save durante render; pasá onClick={save}.", "Usar stopPropagation en todas partes oculta el flujo. Reservalo para una frontera de interacción deliberada.", "No muevas al Effect una operación que pertenece al click o submit: perderías el contexto exacto de la acción."], "Evento = algo que ocurrió; handler = respuesta puntual; Effect = sincronización posterior al render."];
topicDetails.react_actions = ["React moderno", "Una Action representa una transición que puede incluir trabajo asíncrono; useActionState conserva su resultado y pending, mientras useOptimistic muestra una predicción temporal hasta que llega el estado confirmado.", "Estas APIs simplifican flujos de submit, pero no sustituyen validación, autorización, idempotencia ni persistencia del backend.", "const [result, submitAction, isPending] = useActionState(saveProfile, initial)\\nconst [optimisticName, setOptimisticName] = useOptimistic(result.name)\\n\\nfunction rename(name) {\\n  startTransition(() => {\\n    setOptimisticName(name)\\n    submitAction({ name })\\n  })\\n}", "Action con estado pendiente y optimista", ["La Action recibe el estado anterior y el payload, puede ser async y devuelve el nuevo resultado.", "El dispatcher debe ejecutarse como Action —por una action prop o dentro de una Transition— para que React coordine pending.", "useOptimistic cambia lo que se muestra mientras la Action sigue pendiente; después vuelve a la fuente confirmada.", "Con Server Functions, el framework conecta la Action con el servidor; en una SPA común la Action puede llamar a tu cliente HTTP."], ["No confundas Action de React con autorización del servidor: cualquier request debe validarse nuevamente.", "Varias Actions pueden tener semántica de cola; si necesitás paralelismo, deduplicación o cancelación, diseñalo explícitamente.", "Optimismo no es apropiado cuando mentir temporalmente tendría un costo alto, por ejemplo confirmar un pago aún incierto."], "Action coordina una transición async; optimistic state mejora la percepción; el servidor conserva la verdad."];
topicDetails.component_api_patterns = ["Arquitectura", "Una buena API de componente expresa capacidad e intención con props, composición y eventos, sin obligar al consumidor a conocer su implementación.", "En sistemas grandes, la calidad del contrato determina si los componentes se pueden combinar, testear y evolucionar sin una explosión de props booleanas.", "function Dialog({ open, onOpenChange, children }) { /* ... */ }\\n\\n<Dialog open={open} onOpenChange={setOpen}>\\n  <Dialog.Title>Eliminar orden</Dialog.Title>\\n  <Dialog.Actions><ConfirmButton /></Dialog.Actions>\\n</Dialog>", "API controlada y compuesta", ["Una API controlada recibe value/open y emite onChange/onOpenChange; el padre conserva la fuente de verdad.", "children o compound components permiten componer estructura sin agregar una prop por cada variante.", "Render props sirven cuando el consumidor necesita controlar el render usando estado interno expuesto.", "Definí estados, accesibilidad y eventos del contrato antes de elegir el patrón."], ["Muchas props como compact, bordered, editable y selectable crean combinaciones imposibles; preferí variantes o piezas compuestas.", "No expongas detalles internos como setters o nodos DOM si una acción de dominio alcanza.", "Compound components pueden ocultar dependencias: documentá qué piezas requieren contexto y qué jerarquía aceptan."], "Diseñá componentes como contratos: estado, eventos, composición y accesibilidad visibles."];
topicDetails.external_stores = ["Arquitectura", "useSyncExternalStore conecta React con un dato cuyo ciclo de vida vive fuera de React, mediante una suscripción y un snapshot estable.", "Es el contrato usado para integrar stores y APIs externas de forma compatible con render concurrente, no una invitación a globalizar todo el estado.", "function useOnlineStatus() {\\n  return useSyncExternalStore(\\n    callback => { addEventListener(\"online\", callback); addEventListener(\"offline\", callback); return () => { removeEventListener(\"online\", callback); removeEventListener(\"offline\", callback) } },\\n    () => navigator.onLine,\\n    () => true\\n  )\\n}", "subscribe + getSnapshot", ["subscribe registra el callback y devuelve cleanup.", "getSnapshot devuelve el valor actual y debe conservar la misma referencia mientras el store no cambie.", "getServerSnapshot aporta un valor coherente para SSR e hidratación.", "Librerías como Redux o Zustand suelen esconder este contrato detrás de sus hooks."], ["Crear un objeto nuevo en cada getSnapshot puede provocar renders infinitos.", "No uses un store externo para estado que solo pertenece a un componente.", "Suscribirte manualmente con useEffect puede producir tearing: partes de la UI observando versiones distintas durante un render concurrente."], "Para datos externos: suscripción consistente, snapshot estable y cleanup."];
topicDetails.portals_dialogs = ["Web", "createPortal renderiza DOM en otro contenedor, pero el contenido sigue perteneciendo al mismo árbol de React: conserva Context y sus eventos se propagan según ese árbol.", "Los modales necesitan escapar de overflow y stacking contexts, pero el portal solo resuelve ubicación; accesibilidad y foco siguen siendo responsabilidad del componente.", "return createPortal(\\n  <div role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"title\">\\n    <h2 id=\"title\">Confirmar</h2>\\n    <button ref={closeRef} onClick={onClose}>Cerrar</button>\\n  </div>,\\n  document.body\\n)", "Modal accesible dentro de un portal", ["Al abrir, mové foco a un control útil dentro del diálogo.", "Mantené el foco dentro mientras está abierto, cerrá con Escape y devolvé foco al disparador.", "Bloqueá o marcá como inerte el contenido de fondo según la implementación.", "Aunque el DOM esté bajo document.body, un click puede burbujear a ancestros del árbol React."], ["Un z-index enorme no siempre arregla un stacking context; el portal cambia el contenedor DOM.", "Portal no equivale a modal accesible: sin nombre, focus trap y retorno de foco la interacción queda rota.", "Cerrar por cualquier click burbujeado puede causar cierres accidentales; distinguí backdrop y contenido."], "Portal cambia dónde vive el DOM, no quién es su padre conceptual en React."];
topicDetails.server_components = ["Web", "Un Server Component se ejecuta antes del bundle del cliente y puede leer datos cerca del servidor; un Client Component contiene interactividad y se marca con \"use client\" en frameworks que soportan RSC.", "Separarlo de SSR evita una confusión común: SSR produce HTML inicial; RSC además evita enviar al navegador el código del componente de servidor.", "// ProductPage.server.jsx\\nasync function ProductPage({ id }) {\\n  const product = await db.products.find(id)\\n  return <BuyPanel product={{ id: product.id, name: product.name }} />\\n}\\n\\n// BuyPanel.client.jsx\\n\"use client\"\\nfunction BuyPanel({ product }) { /* state y eventos */ }", "Datos en server, interacción en client", ["El Server Component puede acceder al data layer y usar await, pero no useState, effects ni APIs del browser.", "El Client Component recibe props serializables y puede usar estado, eventos y DOM.", "La frontera \"use client\" incluye ese módulo y sus imports en el bundle cliente.", "RSC depende de integración de framework/bundler; no se activa agregando una API aislada a cualquier SPA."], ["\"use server\" no marca Server Components; marca Server Functions.", "Importar una librería pesada desde una frontera client puede empujarla al bundle del navegador.", "No pases conexiones, clases o funciones arbitrarias como props a través de la frontera: los datos deben ser serializables."], "SSR decide cómo nace el HTML; RSC decide qué componentes y código necesitan llegar al browser."];

topicDetails.native_component_contract = ["Design system", "Un componente reutilizable que envuelve un elemento nativo debe preservar las capacidades que el consumidor espera de ese elemento: atributos, eventos, ref, foco y participación en formularios.", "Una ref en el nodo equivocado o un name que deja de llegar al input puede romper integraciones aunque el componente siga viéndose igual.", "type ButtonProps = ComponentPropsWithoutRef<\"button\"> & {\\n  loading?: boolean\\n}\\n\\nconst Button = forwardRef<HTMLButtonElement, ButtonProps>(\\n  ({ className, loading, children, ...rest }, ref) => (\\n    <button ref={ref} className={cx(\"button\", className)} disabled={loading || rest.disabled} {...rest}>\\n      {loading ? <Spinner /> : children}\\n    </button>\\n  )\\n)", "Extender el contrato del elemento real", ["Elegí el elemento semántico que posee el comportamiento base: button, input, a o select.", "Extendé sus props nativas para aceptar id, name, data-*, aria-*, eventos y atributos futuros sin redeclararlos uno por uno.", "Aplicá className, style y ref al nodo significativo que el consumidor necesita estilizar, medir o enfocar.", "Comprobá submit, reset, required, disabled y serialización de FormData cuando el componente participa en un form."], ["Hacer spread sobre un wrapper div preserva TypeScript, pero no el comportamiento del input o button real.", "Cambiar el target de una ref o className es un cambio de contrato aunque las props públicas conserven su nombre.", "No difundas props indiscriminadamente entre varios nodos: documentá cuál es el attachment point principal."], "La envoltura debe sumar diseño sin quitar silenciosamente capacidades de la plataforma.", { tableTitle: "SUPERFICIES NATIVAS", tableLabel: "Qué debe seguir funcionando", table: { columns: ["Superficie", "Contrato observable", "Riesgo al moverla"], rows: [["ref", "Nodo enfocable o medible", "Focus y mediciones rotas"], ["name / value", "Participación en FormData", "El backend no recibe el campo"], ["id / aria-*", "Relaciones semánticas", "Label y descripción desconectados"], ["className / data-*", "Styling y selección", "Integraciones del consumidor rotas"], ["evento", "Target, timing y preventDefault", "Handlers incompatibles"]] }, related: ["refs_dom", "forms_controlled", "events_propagation"] }];
topicDetails.public_component_contract = ["Design system", "La API real de un componente no termina en su interface TypeScript: también incluye callbacks, refs, DOM estable, atributos, clases, estilos, nombres accesibles, stories y cualquier comportamiento que consumidores puedan observar.", "Este modelo permite detectar breaking changes que parecen refactors internos y decidir qué preservar, deprecar o documentar.", "type SelectContract = {\\n  value?: string\\n  defaultValue?: string\\n  onValueChange?: (details: { value: string; reason: \"select\" | \"clear\" }) => void\\n}\\n\\n// También son contrato: ref al trigger, name en el control,\\n// aria-expanded, data-state y la estructura prometida.", "Inventario de superficie observable", ["Listá quién consume el componente: aplicación, CSS, tests, forms, assistive technology y otros componentes.", "Para cada superficie preguntá qué puede observar: tipo, valor, evento, nodo, atributo, estado visual o semántica.", "Separá contrato intencional de detalle accidental, pero tratá una dependencia existente como riesgo de migración aunque no fuera ideal.", "Ante un cambio, preservá compatibilidad o hacé explícito el nuevo contrato con versión, deprecación, documentación y prueba."], ["“Es interno” no alcanza si className, DOM o ref son observables y ya existen consumidores.", "Prometer toda la implementación congela el componente; definí attachment points y contratos deliberados.", "No uses tests como sustituto de una decisión: primero decidí qué debe ser estable y luego protegelo."], "Un refactor deja de ser interno cuando obliga a un consumidor a reaprender algo observable.", { tableTitle: "CONSUMIDORES DEL CONTRATO", tableLabel: "Una misma modificación puede afectar capas distintas", table: { columns: ["Consumidor", "Superficie"], rows: [["TypeScript / IDE", "Props, exports y tipos"], ["React app", "Callbacks, controlled state y composición"], ["Browser / forms", "Eventos, ref, name, validity y reset"], ["CSS / tests", "DOM, clases y data attributes"], ["Assistive technology", "Semántica, nombre, estado y foco"]] }, prompt: "Revisá un cambio que reemplaza <input> por un trigger + popover: ¿qué superficies públicas inventariás antes de aprobarlo?", related: ["native_component_contract", "component_api_patterns"] }];
topicDetails.callback_contracts = ["Design system", "Un callback público define qué ocurrió, cuándo se notifica y qué información estable recibe el consumidor; por eso su payload y timing son parte de la API.", "Eventos posicionales difíciles de extender, objetos sintéticos que imitan mal al browser o callbacks disparados durante cancel pueden convertirse en breaking changes sutiles.", "type ValueChangeDetails = {\\n  value: string\\n  reason: \"select\" | \"clear\" | \"reset\"\\n  originalEvent?: Event\\n}\\n\\ntype Props = {\\n  onValueChange?: (details: ValueChangeDetails) => void\\n}", "Payload extensible con intención explícita", ["Definí el evento de dominio: seleccionar, limpiar, abrir, confirmar o cancelar.", "Elegí si entregás el evento nativo real, un payload de dominio o ambos; no fabriques un objeto que parezca nativo sin cumplir su contrato.", "Preferí un objeto cuando varias piezas relacionadas pueden crecer sin depender del orden posicional.", "Documentá si el callback ocurre antes o después del estado interno y probá que cancel/dismiss no emitan commit."], ["Cambiar (event, item, context) por otra firma rompe consumidores aunque el resultado visual sea idéntico.", "Un callback llamado onChange que solo avisa al cerrar es ambiguo; el nombre debe revelar la transición.", "No filtres metadata que el consumidor necesita para correlacionar la acción con un id estable."], "Callbacks son protocolos: evento, payload, timing y posibilidad de evolución.", { tableTitle: "DISEÑO DEL EVENTO", tableLabel: "Elegí una forma honesta", table: { columns: ["Forma", "Úsala cuando", "Trade-off"], rows: [["Evento nativo", "Importa target/preventDefault", "Ata la API al DOM"], ["Payload de dominio", "Importa la intención", "Debe modelar reason e identidad"], ["Objeto extensible", "La metadata crecerá", "Más explícito que parámetros posicionales"]] }, related: ["events_propagation", "public_component_contract"] }];
topicDetails.controlled_uncontrolled_api = ["Design system", "En modo controlado el consumidor posee el valor y el componente propone cambios mediante callbacks; en modo no controlado el componente posee el valor inicializado por defaultValue.", "Mezclar ambos contratos crea componentes que parecen aceptar cambios externos pero conservan copias internas divergentes.", "function useControllableState({ value, defaultValue, onChange }) {\\n  const controlled = value !== undefined\\n  const [internal, setInternal] = useState(defaultValue)\\n  const current = controlled ? value : internal\\n  const set = next => {\\n    if (!controlled) setInternal(next)\\n    onChange?.(next)\\n  }\\n  return [current, set]\\n}", "Una fuente de verdad por modo", ["Definí exactamente cómo se detecta el modo y mantenelo durante la vida del componente.", "En controlado, renderizá value y no una copia sincronizada con useEffect.", "En no controlado, defaultValue inicializa una vez; cambios posteriores del default no reemplazan interacción del usuario.", "onChange expresa intención en ambos modos, pero solo el owner actualiza la fuente de verdad."], ["Cambiar de controlado a no controlado durante el montaje produce ownership ambiguo; advertí o impedí esa transición.", "No uses value || internal: valores válidos como cadena vacía, 0 o false se perderían.", "Sin una política explícita para reset y clear, cada modo puede terminar mostrando un valor distinto."], "Controlado: el padre decide. No controlado: el componente decide. Nunca los dos a la vez.", { tableTitle: "DOS MODOS, UN CONTRATO", tableLabel: "Quién posee cada decisión", table: { columns: ["Pregunta", "Controlado", "No controlado"], rows: [["Fuente de verdad", "Prop value", "State interno"], ["Valor inicial", "Lo provee el padre", "defaultValue"], ["Cambio", "Callback; padre actualiza", "State interno + callback"], ["Reset", "El padre cambia value", "Se restaura política interna"]] }, related: ["forms_controlled", "lifting_state", "effects"] }];
topicDetails.draft_commit_state = ["Design system", "Los controles complejos suelen necesitar distinguir el valor comprometido del borrador que el usuario edita dentro de un popover, drawer o formulario temporal.", "Sin esa separación, abrir, cerrar, perder foco o presionar Escape puede modificar datos sin intención explícita o descartar cambios que el usuario sí confirmó.", "type State = { committed: Range; draft: Range; open: boolean }\\ntype Action =\\n  | { type: \"edit\"; value: Range }\\n  | { type: \"apply\" }\\n  | { type: \"cancel\" }\\n  | { type: \"reset\" }\\n\\n// apply copia draft → committed; cancel restaura draft.", "Máquina de estados con intención", ["Al abrir, decidí si draft parte del valor committed actual o de una sesión anterior.", "Editar solo cambia draft; Apply valida y compromete; Cancel y Escape restauran sin emitir cambio.", "Clear y Reset no son sinónimos: uno puede representar valor vacío y el otro volver al default o estado del form.", "Enumerá blur, dismiss, submit externo y actualización controlada mientras el panel está abierto."], ["Usar isOpen como señal para copiar props con useEffect es frágil: combina lifecycle visual con ownership del valor.", "No emitas onChange por valores generados que el usuario todavía no pudo confirmar.", "Cerrar por click afuera no debería convertirse accidentalmente en Apply."], "Nombrá cada transición: editar no es confirmar, cerrar no es cancelar y resetear no siempre es limpiar.", { mermaid: "stateDiagram-v2\n  [*] --> closed\n  closed --> editing: open / copy committed to draft\n  editing --> editing: edit draft\n  editing --> closed: apply / validate + commit\n  editing --> closed: cancel or Escape / restore\n  editing --> editing: clear draft\n  closed --> closed: external controlled update", diagramTitle: "Ciclo de vida de un valor editable", related: ["use_state_reducer", "controlled_uncontrolled_api"] }];
topicDetails.library_type_design = ["Design system", "Los tipos de una librería deben describir estados realmente posibles, producir buen autocomplete y exponer contratos que puedan evolucionar sin casts defensivos.", "Un type assertion puede silenciar exactamente el undefined o la variante que luego falla en runtime, mientras un tipo demasiado amplio obliga a cada consumidor a redescubrir la forma válida.", "type LoadState<T> =\\n  | { status: \"idle\" }\\n  | { status: \"loading\" }\\n  | { status: \"success\"; data: T }\\n  | { status: \"error\"; error: Error }\\n\\ntype ButtonProps = ComponentPropsWithoutRef<\"button\"> & {\\n  tone?: \"neutral\" | \"danger\" | undefined\\n}", "Tipos honestos y descubribles", ["Modelá estados excluyentes con unions discriminadas en vez de varias props opcionales combinables.", "Usá tipos nativos para props, eventos y refs cuando el componente preserva ese contrato.", "Evitá as: corregí el origen del dato, validá runtime o estrechá con una condición comprobable.", "Nombrá y exportá tipos de resultado en hooks públicos para detectar cambios deliberadamente."], ["Record<string, string> pierde autocomplete cuando las claves válidas son conocidas.", "unknown en una ref pública oculta el nodo real que el consumidor puede usar.", "TypeScript no valida JSON ni configuración externa: una frontera runtime sigue siendo necesaria."], "El tipo no debe convencer al compilador; debe contarle la verdad al consumidor.", { tableTitle: "TYPE HONESTY", tableLabel: "Síntomas y correcciones", table: { columns: ["Síntoma", "Qué oculta", "Mejor frontera"], rows: [["as SomeType", "Dato no probado", "Validar o estrechar"], ["muchas opcionales", "Estados imposibles", "Union discriminada"], ["Record<string, …>", "Claves conocidas", "Objeto con claves explícitas"], ["ForwardedRef<unknown>", "Target real", "Elemento concreto"]] }, related: ["typescript_react", "native_component_contract"] }];
topicDetails.api_evolution = ["Design system", "Una librería compartida evoluciona mediante compatibilidad, deprecaciones y migraciones explícitas; eliminar o estrechar algo exportado requiere más que actualizar la implementación interna.", "Los consumidores actualizan en tiempos distintos y dependen de IDE, changelog, stories y versiones para entender qué deben cambiar.", "/**\\n * @deprecated Use useDisclosure; useAccordion will be removed in v3.\\n * Migration: const { open, toggle } = useDisclosure()\\n */\\nexport function useAccordion(...) {\\n  return useDisclosure(...)\\n}", "Deprecar antes de remover", ["Detectá el alcance: prop, tipo, hook, export path, callback, DOM o story de un caso previo.", "Si es posible, preservá la API vieja como adaptador y marcala @deprecated con alternativa y horizonte.", "Clasificá estabilidad con alpha/beta cuando el contrato todavía puede cambiar.", "Agregá migration guide, changelog y una prueba o story del uso antiguo hasta completar la transición."], ["Cambiar solo el título del commit no ayuda al consumidor a migrar.", "Borrar una story vieja porque la nueva funciona elimina evidencia de compatibilidad.", "Proxyear tipos de una dependencia también ata tu semver a cambios de esa versión."], "Todo cambio público necesita una historia de adopción, no solo una implementación nueva.", { mermaid: "flowchart LR\n  O[Contrato actual] --> D[Marcar deprecated]\n  D --> A[Adaptador compatible]\n  A --> M[Docs + migration + warning]\n  M --> V[Major version]\n  V --> R[Remoción]", diagramTitle: "Ruta segura para evolucionar una API", related: ["public_component_contract", "library_type_design"] }];
topicDetails.behavior_ownership = ["Design system", "Cuando reemplazás un elemento nativo o una primitive local por UI custom, tu componente pasa a ser dueño de cada comportamiento que antes resolvía esa base.", "Una tarea aparentemente visual puede expandirse a estado, teclado, foco, ARIA, parsing, validación, constraints, eventos y forms; reconocer esa expansión evita reimplementar una plataforma incompleta.", "// Objetivo: customizar la apariencia de un date input\\n// Opción de menor ownership:\\n<label>\\n  Fecha\\n  <input type=\"date\" className=\"custom-date\" {...props} />\\n</label>\\n\\n// Un calendario custom solo se justifica si el requisito\\n// no puede construirse conservando la primitive.", "Mantener la fuente de comportamiento", ["Nombrá el problema original: presentación, normalización, API, comportamiento o accesibilidad.", "Listá qué responsabilidades nuevas aparecen si abandonás la primitive existente.", "Intentá conservar la primitive como fuente de comportamiento y superponer presentación o composición.", "Si lo custom es necesario, documentá el trade-off y construí una matriz de paridad para valores, eventos, constraints, forms, foco y teclado."], ["“Podemos hacerlo en React” no demuestra que debamos poseer toda la conducta.", "Paridad visual no implica paridad funcional con browser, form ni assistive technology.", "Una abstracción thin wrapper deja de ser thin cuando contiene política de estado y lifecycle no declarada."], "Cada comportamiento custom es una responsabilidad de producto que alguien deberá mantener y probar.", { tableTitle: "COSTO DE REEMPLAZAR LA PLATAFORMA", tableLabel: "Responsabilidades que se vuelven propias", table: { columns: ["Área", "Antes", "Después de customizar"], rows: [["Valor", "Browser / primitive", "State y sincronización propios"], ["Interacción", "Teclado y foco nativos", "Modelo completo propio"], ["Validez", "Constraints del control", "Parsing y errores propios"], ["Form", "name/reset/submit", "Hidden input o integración propia"], ["A11y", "Semántica nativa", "Roles, estados y relaciones propias"]] }, prompt: "Te piden rediseñar visualmente un date input. ¿Qué conservarías nativo y qué evidencia exigirías si se reemplaza?", related: ["native_component_contract", "draft_commit_state", "accessibility"] }];
topicDetails.accessible_composites = ["Design system", "Widgets como select, combobox, tabs, tree y menu necesitan un patrón semántico coherente: roles válidos, estado en el elemento correcto, nombres únicos y un modelo completo de teclado y foco.", "Agregar aria-* de forma aislada puede anunciar información falsa; primero se elige la interacción y luego se implementan todas sus relaciones.", "<button\\n  aria-haspopup=\"listbox\"\\n  aria-expanded={open}\\n  aria-controls={listboxId}\\n  onKeyDown={handleTriggerKeys}\\n>\\n  {selectedLabel}\\n</button>\\n<ul id={listboxId} role=\"listbox\" aria-labelledby={labelId}>\\n  {options.map(option => <li role=\"option\" aria-selected={option.id === value}>{option.label}</li>)}\\n</ul>", "Trigger, panel y estado relacionados", ["Preferí un elemento nativo si satisface la experiencia; si no, elegí un patrón WAI-ARIA completo.", "Colocá aria-expanded y aria-controls en el trigger que abre; el panel recibe su role, id y nombre.", "Definí entrada de foco, navegación con flechas, Home/End cuando aplique, Escape, selección y retorno de foco.", "Expresá selected/current/expanded estructuralmente y mantené el texto accesible localizable."], ["No uses aria-selected fuera de un role que lo admite ni role=option sin el contenedor correspondiente.", "Nesting de botones o links crea recorridos ambiguos para teclado y lectores.", "Codificar selected dentro del aria-label mezcla identidad con estado y puede generar nombres duplicados o inestables."], "En accesibilidad, el contrato es el patrón completo, no la suma de atributos sueltos.", { tableTitle: "RELACIONES DEL WIDGET", tableLabel: "Qué pregunta responde cada parte", table: { columns: ["Pieza", "Contrato"], rows: [["Trigger", "Qué abre y si está expandido"], ["Panel", "Qué tipo de colección o diálogo es"], ["Opción", "Identidad y estado seleccionado"], ["Foco", "Dónde entra, se mueve y vuelve"], ["Nombre", "Cómo se anuncia sin depender del aspecto"]] }, related: ["accessibility", "portals_dialogs", "events_propagation"] }];
topicDetails.design_tokens = ["Design system", "Los tokens expresan decisiones semánticas compartidas —color de fondo, spacing, foco, elevación— y permiten que un componente funcione en temas presentes y futuros.", "Un literal aislado puede fallar en otro tema; una CSS variable innecesaria también agrega indirección. La abstracción debe representar una decisión o una relación real.", ".select {\\n  padding-inline: var(--space-3);\\n  color: var(--control-fg);\\n  background: var(--control-bg);\\n  border-color: var(--control-border);\\n}\\n.select[data-state=\"open\"] {\\n  border-color: var(--control-border-active);\\n}", "Tokens semánticos y estados visibles", ["Usá tokens semánticos cuando el valor debe adaptarse al tema; no elijas un color por cómo se ve en un solo fondo.", "Si dos cálculos deben cambiar juntos, una variable local puede expresar esa invariancia.", "Exponé estados estables mediante data attributes o clases deliberadas para styling y visual regression.", "Probá hover, focus-visible, disabled, error, selected y open en todos los temas soportados."], ["Crear una variable para cada literal sin reutilización ni cálculo aumenta navegación y tamaño sin sumar una decisión.", "Codificar selectores para una lista cerrada de temas impide extensiones futuras.", "Cambiar clases o data attributes documentados puede ser un breaking change para consumidores que extienden estilos."], "Tokenizá decisiones, no números; y tratá los hooks de styling prometidos como contrato.", { tableTitle: "NIVELES DE VALOR", tableLabel: "Elegí el nivel que expresa la intención", table: { columns: ["Valor", "Ejemplo", "Cuándo"], rows: [["Token global", "--control-bg", "Decisión semántica entre temas"], ["Variable local", "--trigger-size", "Acoplar cálculos del componente"], ["Literal", "1px / currentColor", "Valor local obvio sin eje de cambio"]] }, related: ["styling_assets", "public_component_contract"] }];
topicDetails.resilient_ui = ["Design system", "Una UI reutilizable debe adaptarse a contenido real, traducciones, zoom, preferencias del sistema, densidad y temas que el autor no probó manualmente.", "Widths y heights rígidos suelen codificar el mock en vez del contrato; la calidad aparece cuando el layout conserva significado bajo entradas extremas.", ".card {\\n  inline-size: min(100%, 32rem);\\n  min-inline-size: 0;\\n}\\n.card__title {\\n  overflow-wrap: anywhere;\\n}\\n@media (prefers-reduced-motion: reduce) {\\n  .card { transition: none; }\\n}", "Layout gobernado por contenido y constraints", ["Probá copy corta, larga, localizada y valores vacíos sin cambiar la estructura semántica.", "Preferí min/max, flex/grid y tamaño intrínseco antes que reservar altura para una cantidad fija de líneas.", "Asegurá zoom, reflow, reduced motion, contraste y foco visibles.", "Separá identidad accesible de detalles visuales: un borde blanco no cambia qué significa un ícono de warning."], ["Un min-width por defecto puede impedir que el consumidor use el componente en un layout flexible.", "Altura fija deja espacio fantasma o corta contenido al aumentar fuente o traducir.", "Hardcodear texto accesible en inglés dentro de una primitive reusable bloquea localización."], "Diseñá para variación de contenido y entorno, no solo para el screenshot de referencia.", { prompt: "¿Cómo probarías una card con título alemán largo, zoom 200%, tema no conocido y reduced motion?", related: ["design_tokens", "accessibility"] }];
topicDetails.vendor_boundaries = ["Design system", "Una frontera de vendor decide qué parte de una librería externa pasa a ser dependencia directa de tus consumidores y qué parte queda adaptada detrás de una API propia.", "Reexportar tipos o helpers sin una política puede acoplar tu semver a la versión del vendor; esconder todo también obliga a mantener un wrapper que solo repite la API.", "// vendor/tanstack-table.ts\\nexport { getCoreRowModel } from \"@tanstack/react-table\"\\nexport type { Row } from \"@tanstack/react-table\"\\n\\n// Nuestra policy vive en una frontera nombrada:\\nexport function createMagneticTable(options) {\\n  return useReactTable({ getCoreRowModel: getCoreRowModel(), ...options })\\n}", "Vendor aislado, policy propia", ["Identificá si ofrecés una façade estable, un adapter de dominio o simplemente un reexport versionado.", "Centralizá imports del vendor cuando necesitás controlar versión, polyfills o reemplazo.", "No filtres capacidades útiles sin razón: cada diferencia respecto de la primitive crea una regla que mantener.", "Documentá qué tipos externos forman parte de tu API y qué upgrade sería breaking."], ["Un wrapper que refleja cada opción agrega otra API sin reducir complejidad.", "Imports relativos profundos saltan la frontera pública y pueden romperse con reorganización interna.", "Duplicar manualmente lógica ya provista por el vendor puede producir dos caminos con comportamiento distinto."], "La frontera debe reducir acoplamiento o concentrar policy; si no hace ninguna, no está ganando su costo.", { tableTitle: "TIPOS DE FRONTERA", tableLabel: "No todas prometen lo mismo", table: { columns: ["Frontera", "Promesa", "Costo"], rows: [["Reexport", "Misma capacidad/versionada", "Semver ligado al vendor"], ["Façade", "Subset estable", "Mantener traducción"], ["Adapter", "Contrato del dominio", "Mapear ambos modelos"]] }, related: ["component_architecture", "library_type_design"] }];
topicDetails.proof_strategy = ["Design system", "Un componente público necesita evidencia proporcional a sus contratos: tipos para compilación, tests de comportamiento, browser tests para plataforma, stories/VR para estados visuales y documentación para trade-offs.", "Una suite grande no da confianza si prueba líneas internas y omite el callback, ref, form, teclado o estado visual que realmente puede romperse.", "it(\"submits the selected value\", async () => {\\n  const user = userEvent.setup()\\n  render(<form onSubmit={submit}><Select name=\"role\" options={roles} /></form>)\\n  await user.click(screen.getByRole(\"button\", { name: /role/i }))\\n  await user.click(screen.getByRole(\"option\", { name: \"Admin\" }))\\n  await user.click(screen.getByRole(\"button\", { name: /save/i }))\\n  expect(submit).toHaveBeenCalledWith(expect.objectContaining({ role: \"admin\" }))\\n})", "Una prueba que protege el contrato", ["Escribí la afirmación observable antes de elegir herramienta: qué haría un usuario o consumidor.", "Usá RTL + userEvent para semántica y comportamiento React; evitá tests que solo verifican que render no explota.", "Usá browser/E2E para layout, foco real, APIs del navegador y conductas que jsdom no modela fielmente.", "Agregá stories y visual regression para estados open, selected, error, disabled, focus y temas; TSDoc para invariantes no obvias."], ["Un snapshot amplio cambia por ruido y no explica qué contrato se rompió.", "fireEvent salta secuencias reales que userEvent sí reproduce.", "Una story del happy path no prueba overlays abiertos, copy larga ni temas alternativos.", "No dupliques el mismo test en capas distintas: cada harness debe proteger un riesgo que sabe observar."], "Elegí evidencia por contrato, no por comodidad del framework de tests.", { tableTitle: "MATRIZ DE EVIDENCIA", tableLabel: "Herramienta según el riesgo", table: { columns: ["Riesgo", "Prueba principal"], rows: [["Props / tipos / exports", "Type tests + build del consumidor"], ["Eventos / state / semántica", "RTL + userEvent"], ["Foco / layout / browser API", "Playwright u otro browser real"], ["Tema / estado visual", "Storybook + visual regression"], ["Invariante no obvia", "TSDoc / docs + test focalizado"]] }, related: ["testing_rtl", "testing_async", "design_tokens"] }];
topicDetails.scope_reviewability = ["Design system", "Revisar como maintainer significa proteger contratos con evidencia, distinguir bugs de preguntas de intención y exigir que el cambio posea la menor superficie de comportamiento necesaria.", "El objetivo no es imponer preferencias: es reducir lo que consumidores y futuros mantenedores deberán reaprender.", "// Antes de comentar:\\n// 1. ¿Qué problema intenta resolver el cambio?\\n// 2. ¿Qué superficie observable cambió?\\n// 3. ¿Qué evidencia demuestra el riesgo?\\n// 4. ¿Existe una primitive o precedente local?\\n// 5. ¿Es Request, Question, Suggestion o polish?", "Del diff a una observación de stewardship", ["Congelá el scope y separá API, DOM/a11y, state, tipos, styling, proof y boundaries.", "Buscá el precedente local más cercano antes de llamar drift a una decisión.", "Si una tarea visual empezó a poseer state, parsing, focus o keyboard, cuestioná el scope además de señalar bugs concretos.", "Escribí el porqué y pedí preservar el contrato; no prescribas un helper viejo salvo que siga siendo la policy actual.", "Calibrá lenguaje: directo para un bug probado, pregunta para intención incierta y non-blocking para polish."], ["Complejidad no se mide solo en líneas: un hook pequeño puede esconder una policy difícil de descubrir.", "No agrupes lifecycle distintos como duplicados: cuándo se confirma y qué valor es válido son preguntas diferentes.", "No uses mayoría de opiniones como evidencia; un solo hallazgo fuerte puede ser suficiente."], "Senior review = contexto + contrato + evidencia + una petición proporcional.", { tableTitle: "CALIBRACIÓN", tableLabel: "Cómo convertir evidencia en comentario", table: { columns: ["Evidencia", "Intent típico"], rows: [["Bug reproducible", "Request directa"], ["Contrato puede romperse", "Request o Question"], ["Intención/producto incierto", "Question"], ["Patrón más claro, actual válido", "Suggestion"], ["Polish sin riesgo demostrado", "Non-blocking"]] }, prompt: "Un MR para cambiar colores reemplaza un input nativo por un popover custom. Escribí los tres comentarios de mayor señal y justificá por qué no comentarías el resto.", related: ["public_component_contract", "behavior_ownership", "proof_strategy"] }];
topicDetails.case_design_system_select = ["Caso integrador", "Diseñar un Select reutilizable obliga a decidir si alcanza el select nativo o si el producto necesita un widget compuesto; desde esa decisión se derivan ownership, API, estado, accesibilidad, forms, styling y pruebas.", "Es un excelente ejercicio senior porque cada mejora visual puede crear obligaciones no visibles para aplicaciones consumidoras.", "type SelectProps = Omit<ComponentPropsWithoutRef<\"button\">, \"value\" | \"defaultValue\" | \"onChange\"> & {\\n  name?: string\\n  value?: string\\n  defaultValue?: string\\n  options: Array<{ id: string; label: ReactNode; disabled?: boolean }>\\n  onValueChange?: (details: { value: string; reason: \"select\" | \"clear\" }) => void\\n}\\n\\n// triggerRef apunta al control; hidden input participa en el form.\\n// El listbox usa ids estables, navegación de teclado y tokens.", "Contrato mínimo de un Select custom", ["Confirmá requisitos que el select nativo no cubre; si son solo apariencia, mantenelo como behavior source.", "Definí controlado/no controlado, identidad estable, clear/reset y timing de onValueChange.", "Preservá id, name, ref, disabled, required, form submit y reset mediante el nodo adecuado o integración explícita.", "Implementá trigger/listbox/options como un patrón completo: nombre, expanded, controls, selección, teclado y foco.", "Expresá estados con tokens/data-state y probá RTL, browser, stories/VR, temas y migración desde la API previa."], ["Usar label como id rompe cuando se traduce o se repite.", "Cerrar el panel no debe confirmar un draft ni emitir un evento de selección.", "Una div con onClick no hereda form, teclado, foco ni semántica de select.", "No expongas simultáneamente dos entry points para la misma policy sin decidir cuál es autoridad."], "El Select no es un popover bonito: es un contrato coordinado entre React, browser, form, accesibilidad y consumidores.", { mermaid: "flowchart TD\n  R[Requisitos] --> N{¿Alcanza select nativo?}\n  N -->|Sí| NS[Estilizar y preservar behavior nativo]\n  N -->|No| O[Asumir ownership custom]\n  O --> API[API: value/defaultValue/events/ref]\n  O --> ST[State: draft/commit/clear/reset]\n  O --> AX[A11y: trigger/listbox/keyboard/focus]\n  O --> FM[Form: name/required/submit/reset]\n  O --> VS[Visual: tokens/themes/content]\n  API --> P[Proof matrix]\n  ST --> P\n  AX --> P\n  FM --> P\n  VS --> P\n  P --> EV[Evolución y migration]", diagramTitle: "Decisiones de un componente público", prompt: "Diseñá en vivo un Select con búsqueda, clear, modo controlado/no controlado y submit de form. Explicá cada contrato antes del código.", related: ["native_component_contract", "controlled_uncontrolled_api", "accessible_composites", "proof_strategy"] }];

Object.assign(topicDetails, INTERVIEW_EXPANSION_DETAILS);

const lessonAuditOverrides = {
  effects: {
    explanation: "Partí de esta pregunta: “¿qué sistema externo debe quedar sincronizado con este render?”. Si la respuesta es una conexión, timer, listener o API imperativa, el Effect configura esa relación después del commit y su cleanup deshace la versión anterior. Si la operación ocurre porque el usuario hizo click, pertenece al handler; si el valor puede calcularse con props y state, pertenece al render.",
  },
  optimistic_ui: {
    explanation: "Hay dos niveles comunes. TanStack Query permite modificar temporalmente la cache compartida y restaurar un snapshot si falla la mutación. useOptimistic permite derivar una vista temporal durante una Action. En ambos casos la UI está haciendo una predicción: debe mostrar qué sigue pendiente y reconciliarse con la respuesta canónica del servidor.",
    code: "const [optimisticTodos, addOptimisticTodo] = useOptimistic(\n  todos,\n  (current, todo) => [...current, { ...todo, pending: true }]\n)\n\nstartTransition(async () => {\n  addOptimisticTodo(draft)\n  await createTodo(draft)\n})",
    codeLabel: "Predicción local durante una Action",
  },
  ssr_hydration: {
    explanation: "En SSR el servidor ejecuta React y envía HTML visible. El navegador muestra ese HTML antes de descargar todo el JavaScript; luego hydrateRoot vuelve a calcular el mismo árbol y conecta eventos sobre los nodos existentes. Si el primer resultado del cliente difiere —por fecha, random, localStorage o markup inválido— aparece un hydration mismatch. Esto no es todavía Server Components: el código de esos componentes tradicionales también llega al cliente.",
  },
  case_dashboard: {
    explanation: "El flujo empieza en la URL porque filtros y página deben poder compartirse. Esos valores forman la queryKey; la cache devuelve datos frescos o conserva los anteriores mientras obtiene la nueva página. La tabla no copia esos datos a state local. Cada widget tiene su propio límite de loading/error, y una tabla realmente grande se pagina en servidor o virtualiza según el volumen.",
    mermaid: "flowchart LR\n  U[URL: filtros y página] --> Q[queryKey]\n  Q --> C[Cache TanStack Query]\n  C -->|fresh| V[Widgets y tabla]\n  C -->|stale o missing| A[Rails API]\n  A --> C\n  V --> M[Mutación]\n  M -->|success| I[Invalidar queries]\n  I --> C\n  M -->|error| E[Mensaje y recuperación]",
    diagramTitle: "Datos, cache e invalidación del dashboard",
  },
  case_auth: {
    explanation: "Al arrancar, la app entra en estado checking y consulta o renueva la sesión antes de decidir una ruta. Las requests normales llevan el access token; un único coordinador maneja el primer 401, intenta refresh y reintenta las requests en espera. Si refresh falla, limpia usuario y cache sensible. Un 403 no se refresca: el usuario sí está identificado, pero no tiene permiso.",
    mermaid: "sequenceDiagram\n  participant R as React\n  participant A as Rails API\n  participant S as Session store\n  R->>A: Request + access token\n  A-->>R: 401 expirado\n  R->>A: POST /refresh + cookie HttpOnly\n  A->>S: valida y rota refresh\n  S-->>A: sesión válida\n  A-->>R: nuevo access token\n  R->>A: reintenta request una vez\n  A-->>R: 200 o 403",
    diagramTitle: "Refresh coordinado sin loops",
  },
  case_checkout: {
    explanation: "Modelalo como una máquina de estados, no como un boolean loading. editing permite corregir campos; submitting bloquea duplicados; requires_action espera un paso del proveedor; pending significa que el resultado todavía no es definitivo; success y failed muestran salidas recuperables. La idempotency key representa el intento y se conserva si reintentás tras un timeout ambiguo.",
    mermaid: "stateDiagram-v2\n  [*] --> editing\n  editing --> submitting: submit válido\n  submitting --> editing: error de validación\n  submitting --> requires_action: autenticación de pago\n  requires_action --> pending: acción completada\n  submitting --> pending: respuesta incierta\n  pending --> success: backend confirma\n  pending --> failed: backend rechaza\n  failed --> submitting: retry con misma intención\n  success --> [*]",
    diagramTitle: "Máquina de estados del checkout",
  },
};

Object.assign(topicDetails, SENIOR_TOPIC_DETAILS);

const nodes = data.map(([id, label, cat]) => {
  const detail = topicDetails[id];
  const correction = REACT_CONCEPTUAL_CORRECTIONS[id] ?? {};
  const baseLesson = makeLesson(...detail);
  const layeredLesson = {
    ...baseLesson,
    ...(lessonAuditOverrides[id] ?? {}),
    audit: REACT_AUDIT_NOTES[id] ?? REACT_ADVANCED_AUDIT_NOTES[id] ?? baseLesson.audit ?? null,
    ...correction,
    ...(REACT_ARCHITECTURE_REVIEW[id] ?? {}),
  };
  const explanationUsesAudit = !layeredLesson.explanation && Boolean(layeredLesson.audit);
  const sources = [...(layeredLesson.sources ?? []), ...getSupplementalReactSources(id)]
    .filter((item, index, items) => items.findIndex((candidate) => candidate.href === item.href) === index);
  const docNotes = [...(layeredLesson.docNotes ?? []), ...(REACT_REVIEW_NOTES[id] ?? [])]
    .filter((item, index, items) => items.indexOf(item) === index);
  const lesson = {
    ...layeredLesson,
    explanation: layeredLesson.explanation
      ?? [layeredLesson.audit?.primer, layeredLesson.audit?.example].filter(Boolean).join(" "),
    explanationUsesAudit,
    docNotes,
    sources,
  };
  return {
    id,
    label,
    cat,
    lesson,
    interviewQuestions: getInterviewQuestionsForNode(id),
    priority: priorityOrder.indexOf(id) + 1,
    prerequisites: prerequisites[id] ?? [],
  };
});
const edges = Object.entries(prerequisites).flatMap(([target, required]) => required.map((source) => [source, target]));

export default {
  id: "react",
  label: "React entrevistas",
  title: "React interview map",
  subtitle: "De modelo mental y entrega de features a browser, producción, design systems y liderazgo frontend.",
  categories,
  categoryContext,
  nodes,
  edges,
  nodeIds: new Set(nodes.map((node) => node.id)),
  interviewQuestions: REACT_INTERVIEW_QUESTIONS,
  interviewQuestionSource: GREATFRONTEND_REACT_SOURCE,
  milestones: REACT_MILESTONES,
  seniorityBands: REACT_SENIORITY_BANDS,
};
