export const GREATFRONTEND_REACT_SOURCE = "https://www.greatfrontend.com/blog/100-react-interview-questions-straight-from-ex-interviewers";

const titles = [
  "¿Qué es React y cuáles son sus rasgos principales?",
  "¿Qué es JSX y cómo se transforma?",
  "¿Qué intenta expresar la metáfora de Virtual DOM?",
  "¿Cómo funciona el árbol virtual y cuáles son sus costos?",
  "¿Qué diferencia hay entre React node, element y component?",
  "¿Para qué sirven los Fragments?",
  "¿Qué propósito tiene key?",
  "¿Qué falla al usar el índice como key?",
  "¿En qué se diferencian props y state?",
  "¿En qué se diferencian class y function components?",
  "¿Cuándo mantendrías o escribirías una clase?",
  "¿Qué es React Fiber a nivel útil para una entrevista?",
  "¿Qué es reconciliation?",
  "¿Cómo se diferencian Shadow DOM y el árbol de React?",
  "¿Qué diferencia hay entre componentes controlados y no controlados?",
  "¿Cómo y por qué se eleva el state?",
  "¿Qué eran Pure Components y cuál es su equivalente moderno?",
  "¿Qué diferencia hay entre createElement y cloneElement?",
  "¿Qué rol tenían PropTypes y qué cambió en React 19?",
  "¿Qué significa que un componente sea stateless?",
  "¿Qué significa que un componente sea stateful?",
  "¿Cómo tipar props hoy?",
  "¿Por qué React desaconseja mutar state?",
  "¿Qué aportan los Hooks?",
  "¿Cuáles son las reglas de Hooks y por qué existen?",
  "¿Cómo se diferencian useEffect y useLayoutEffect?",
  "¿Qué controla realmente el array de dependencias?",
  "¿Cuándo corresponde useRef?",
  "¿Para qué sirve la forma updater de setState o un setter?",
  "¿Cuándo tiene sentido useCallback?",
  "¿Cuándo tiene sentido useMemo?",
  "¿Cuándo elegir useReducer?",
  "¿Para qué sirve useId y para qué no?",
  "¿Cómo se diseña un custom Hook?",
  "¿Qué significa que un componente se vuelva a renderizar?",
  "¿Para qué se usó forwardRef y qué cambia en React 19?",
  "¿Qué errores captura un Error Boundary?",
  "¿Qué coordina Suspense?",
  "¿Qué es hidratación?",
  "¿Para qué sirve un Portal?",
  "¿Qué comprueba Strict Mode?",
  "¿Cómo funciona code splitting?",
  "¿Cómo reducir renders causados por Context?",
  "¿Qué es el patrón Flux?",
  "¿Qué significa flujo de datos unidireccional?",
  "¿Qué costos y errores introduce Context?",
  "¿Cuáles son anti-patrones frecuentes en React?",
  "¿Cómo elegir entre state local, Context y un store externo?",
  "¿Qué ocurre al llamar un setter de state?",
  "¿Qué es prop drilling y cuándo es un problema?",
  "¿Cómo se implementa lazy loading?",
  "¿Cómo funcionan los eventos de React y el evento nativo?",
  "¿Cómo se traduce el lifecycle de clases al modelo moderno?",
  "¿Qué capacidades concurrentes ofrece React?",
  "¿Cómo prioriza React actualizaciones distintas?",
  "¿Cómo evitar bloquear la UI con trabajo costoso?",
  "¿Qué aporta SSR?",
  "¿Qué aporta la generación estática?",
  "¿Qué es un Higher-Order Component?",
  "¿Qué intenta separar container/presentational?",
  "¿Qué es un render prop?",
  "¿Cómo funciona composición en React?",
  "¿Cómo responder al cambio de tamaño del browser o contenedor?",
  "¿Cómo cargar datos async sin perder estados intermedios?",
  "¿Qué fallas son comunes al hacer data fetching?",
  "¿Qué problema resuelve React Router?",
  "¿Cómo funcionan rutas dinámicas y params?",
  "¿Cómo funcionan rutas anidadas y Outlet?",
  "¿Cuándo usar BrowserRouter o HashRouter?",
  "¿Qué diferencia hay entre un router y una API de history?",
  "¿Qué modos y routers ofrece React Router?",
  "¿Qué diferencia práctica hay entre push y replace?",
  "¿Cómo navegar programáticamente?",
  "¿Cómo diseñar una ruta privada sin confundirla con autorización?",
  "¿Cómo representar la ruta activa?",
  "¿Cómo manejar una ruta no encontrada?",
  "¿Cómo leer y escribir search params?",
  "¿Cómo redirigir después de login sin romper Back ni crear open redirects?",
  "¿Cómo entregar datos o dependencias a una route?",
  "¿Cómo localizar una aplicación React?",
  "¿Qué problema resuelve React Intl?",
  "¿Qué capacidades principales ofrece React Intl?",
  "¿Qué diferencia hay entre componentes y API imperativa de formato?",
  "¿Cómo usar un mensaje localizado como placeholder accesible?",
  "¿Cómo acceder al locale actual?",
  "¿Cómo formatear fechas correctamente?",
  "¿Cómo estructurar una estrategia de tests React?",
  "¿Qué rol cumple Jest o Vitest?",
  "¿Qué filosofía tiene React Testing Library?",
  "¿Cómo probar un componente desde el comportamiento?",
  "¿Cómo probar trabajo async?",
  "¿Cómo simular o interceptar requests?",
  "¿Cómo probar un Hook usado por un componente?",
  "¿Cuándo probar un custom Hook con renderHook?",
  "¿Qué era shallow rendering y por qué se desaconseja?",
  "¿Cuándo aporta o estorba un snapshot?",
  "¿Cómo probar un componente que consume Context?",
  "¿Cómo probar uno conectado a Redux u otro store?",
  "¿Qué diferencia hay entre shallow y render DOM?",
  "¿Qué era react-test-renderer y qué cambió en React 19?",
  "¿Qué novedades importantes reunió React 19?",
  "¿Qué significa Action en React?",
  "¿Qué estado coordina useActionState?",
  "¿Cómo funciona useOptimistic?",
  "¿Cómo funciona use(Promise o Context) y cómo difiere de fetch en un Effect?",
  "¿Qué es un Server Component?",
  "¿Dónde está la frontera entre Server y Client Components?",
  "¿Qué hace React Compiler y qué no corrige?",
  "¿Cómo se diferencian useTransition y useDeferredValue?",
  "¿Cómo funciona una función en form action?",
];

const targets = {
  1: ["react_mental_model"],
  2: ["jsx_rendering", "react_values_elements"],
  3: ["render_reconciliation"],
  4: ["render_reconciliation", "performance"],
  5: ["react_values_elements"],
  6: ["react_values_elements"],
  7: ["keys_lists"],
  8: ["keys_lists"],
  9: ["components_props", "state_updates"],
  10: ["legacy_react_apis"],
  11: ["legacy_react_apis", "error_boundaries"],
  12: ["render_reconciliation", "transitions_concurrency"],
  13: ["render_reconciliation"],
  14: ["render_reconciliation", "browser_rendering_pipeline"],
  15: ["forms_controlled", "controlled_uncontrolled_api"],
  16: ["lifting_state"],
  17: ["legacy_react_apis", "memoization"],
  18: ["react_values_elements", "component_api_patterns"],
  19: ["legacy_react_apis", "typescript_react"],
  20: ["components_props"],
  21: ["components_props", "state_updates"],
  22: ["typescript_react"],
  23: ["state_updates"],
  24: ["hooks_rules"],
  25: ["hooks_rules"],
  26: ["effect_timing_strict_mode"],
  27: ["effect_dependencies"],
  28: ["refs_dom"],
  29: ["state_updates", "legacy_react_apis"],
  30: ["memoization"],
  31: ["memoization"],
  32: ["use_state_reducer"],
  33: ["useid_identity"],
  34: ["custom_hooks"],
  35: ["render_reconciliation"],
  36: ["legacy_react_apis", "native_component_contract"],
  37: ["error_boundaries"],
  38: ["suspense_lazy", "react_resources_activity"],
  39: ["ssr_hydration", "rendering_strategies"],
  40: ["portals_dialogs"],
  41: ["effect_timing_strict_mode"],
  42: ["suspense_lazy"],
  43: ["context", "memoization"],
  44: ["react_patterns_history", "state_management"],
  45: ["react_mental_model", "lifting_state"],
  46: ["context"],
  47: ["component_architecture", "effects", "derived_state"],
  48: ["state_management"],
  49: ["state_updates", "render_reconciliation"],
  50: ["lifting_state", "context"],
  51: ["suspense_lazy"],
  52: ["events_propagation"],
  53: ["legacy_react_apis", "effect_timing_strict_mode"],
  54: ["transitions_concurrency"],
  55: ["transitions_concurrency", "render_reconciliation"],
  56: ["performance", "event_loop_tasks"],
  57: ["ssr_hydration", "rendering_strategies"],
  58: ["rendering_strategies"],
  59: ["react_patterns_history"],
  60: ["react_patterns_history", "component_architecture"],
  61: ["react_patterns_history"],
  62: ["components_props", "react_patterns_history"],
  63: ["responsive_browser_subscriptions"],
  64: ["data_fetching", "server_state"],
  65: ["async_race", "data_fetching"],
  66: ["routing"],
  67: ["routing", "routing_data_apis"],
  68: ["routing_data_apis"],
  69: ["routing"],
  70: ["routing"],
  71: ["routing", "routing_data_apis"],
  72: ["routing"],
  73: ["routing"],
  74: ["routing", "auth_frontend", "case_auth"],
  75: ["routing"],
  76: ["routing_data_apis", "error_boundaries"],
  77: ["routing"],
  78: ["case_auth", "routing"],
  79: ["routing_data_apis", "component_api_patterns"],
  80: ["i18n_localization"],
  81: ["i18n_localization"],
  82: ["i18n_localization"],
  83: ["i18n_localization"],
  84: ["i18n_localization", "accessibility"],
  85: ["i18n_localization"],
  86: ["i18n_localization"],
  87: ["testing_strategy", "testing_tools_legacy"],
  88: ["testing_tools_legacy"],
  89: ["testing_rtl", "testing_tools_legacy"],
  90: ["testing_rtl"],
  91: ["testing_async"],
  92: ["testing_async", "testing_tools_legacy"],
  93: ["testing_rtl", "custom_hooks"],
  94: ["testing_tools_legacy", "custom_hooks"],
  95: ["testing_tools_legacy"],
  96: ["testing_tools_legacy", "testing_strategy"],
  97: ["testing_rtl", "context"],
  98: ["testing_rtl", "state_management"],
  99: ["testing_tools_legacy"],
  100: ["testing_tools_legacy"],
  101: ["react_actions", "server_components", "react_compiler", "react_resources_activity"],
  102: ["react_actions"],
  103: ["react_actions"],
  104: ["optimistic_ui", "react_actions"],
  105: ["react_resources_activity", "effects"],
  106: ["server_components"],
  107: ["server_components"],
  108: ["react_compiler"],
  109: ["transitions_concurrency"],
  110: ["react_actions"],
};

export const REACT_INTERVIEW_QUESTIONS = titles.map((title, index) => ({
  id: index + 1,
  title,
  nodeIds: targets[index + 1] ?? [],
}));

export function getInterviewQuestionsForNode(nodeId) {
  return REACT_INTERVIEW_QUESTIONS.filter((question) => question.nodeIds.includes(nodeId));
}
