const source = (label, href) => ({ label, href });

const SOURCES = {
  mdnClosures: source("Closures — MDN", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures"),
  mdnPromises: source("Using promises — MDN", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises"),
  reactThinking: source("Thinking in React", "https://react.dev/learn/thinking-in-react"),
  reactRenderCommit: source("Render and Commit — React", "https://react.dev/learn/render-and-commit"),
  reactProps: source("Passing Props to a Component — React", "https://react.dev/learn/passing-props-to-a-component"),
  reactJsx: source("Writing Markup with JSX — React", "https://react.dev/learn/writing-markup-with-jsx"),
  reactEvents: source("Responding to Events — React", "https://react.dev/learn/responding-to-events"),
  reactSnapshot: source("State as a Snapshot — React", "https://react.dev/learn/state-as-a-snapshot"),
  reactBatching: source("Queueing a Series of State Updates — React", "https://react.dev/learn/queueing-a-series-of-state-updates"),
  reactHooksRules: source("Rules of Hooks — React", "https://react.dev/reference/rules/rules-of-hooks"),
  reactUse: source("use — React", "https://react.dev/reference/react/use"),
  reactCustomHooks: source("Reusing Logic with Custom Hooks — React", "https://react.dev/learn/reusing-logic-with-custom-hooks"),
  reactReducer: source("Extracting State Logic into a Reducer — React", "https://react.dev/learn/extracting-state-logic-into-a-reducer"),
  reactSharingState: source("Sharing State Between Components — React", "https://react.dev/learn/sharing-state-between-components"),
  reactStateShape: source("Choosing the State Structure — React", "https://react.dev/learn/choosing-the-state-structure"),
  reactRefs: source("Referencing Values with Refs — React", "https://react.dev/learn/referencing-values-with-refs"),
  reactEffects: source("Synchronizing with Effects — React", "https://react.dev/learn/synchronizing-with-effects"),
  reactEffectLifecycle: source("Lifecycle of Reactive Effects — React", "https://react.dev/learn/lifecycle-of-reactive-effects"),
  reactEffectDependencies: source("Removing Effect Dependencies — React", "https://react.dev/learn/removing-effect-dependencies"),
  reactUseEffect: source("useEffect — React", "https://react.dev/reference/react/useEffect"),
  reactTransitions: source("useTransition — React", "https://react.dev/reference/react/useTransition"),
  reactKeys: source("Rendering Lists — React", "https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key"),
  reactIdentity: source("Preserving and Resetting State — React", "https://react.dev/learn/preserving-and-resetting-state"),
  reactMemo: source("memo — React", "https://react.dev/reference/react/memo"),
  reactUseMemo: source("useMemo — React", "https://react.dev/reference/react/useMemo"),
  reactCompiler: source("React Compiler — React", "https://react.dev/learn/react-compiler/introduction"),
  reactProfiler: source("<Profiler> — React", "https://react.dev/reference/react/Profiler"),
  reactLazy: source("lazy — React", "https://react.dev/reference/react/lazy"),
  reactSuspense: source("<Suspense> — React", "https://react.dev/reference/react/Suspense"),
  reactBoundary: source("Error Boundaries — React", "https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary"),
  reactPortal: source("createPortal — React", "https://react.dev/reference/react-dom/createPortal"),
  reactHydration: source("hydrateRoot — React", "https://react.dev/reference/react-dom/client/hydrateRoot"),
  reactRsc: source("Server Components — React", "https://react.dev/reference/rsc/server-components"),
  reactSecurityRsc: source("React Server Components security advisory", "https://react.dev/blog/2025/12/03/critical-security-vulnerability-in-react-server-components"),
  reactTypes: source("TypeScript — React", "https://react.dev/learn/typescript"),
  reactVersions: source("React Versions", "https://react.dev/versions"),
  mdnForms: source("Web forms — MDN", "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms"),
  mdnButton: source("<button> — MDN", "https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button"),
  mdnAbort: source("AbortController — MDN", "https://developer.mozilla.org/en-US/docs/Web/API/AbortController"),
  mdnHistory: source("History API — MDN", "https://developer.mozilla.org/en-US/docs/Web/API/History_API"),
  mdnCssProperties: source("CSS custom properties — MDN", "https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties"),
  mdnIntl: source("Intl — MDN", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl"),
  mdnEventLoop: source("JavaScript execution model — MDN", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model"),
  mdnHttpCache: source("HTTP caching — MDN", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching"),
  mdnWebSocket: source("WebSocket API — MDN", "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API"),
  mdnOnline: source("Navigator.onLine — MDN", "https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine"),
  mdnTrustedTypes: source("Trusted Types API — MDN", "https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API"),
  waiPatterns: source("WAI-ARIA Authoring Practices", "https://www.w3.org/WAI/ARIA/apg/patterns/"),
  waiCombobox: source("Combobox Pattern — WAI-ARIA APG", "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/"),
  wcagReflow: source("WCAG: Reflow", "https://www.w3.org/WAI/WCAG22/Understanding/reflow.html"),
  testingLibrary: source("Guiding Principles — Testing Library", "https://testing-library.com/docs/guiding-principles"),
  testingUserEvent: source("user-event — Testing Library", "https://testing-library.com/docs/user-event/intro/"),
  msw: source("Mock Service Worker docs", "https://mswjs.io/docs/"),
  playwright: source("Playwright: Best Practices", "https://playwright.dev/docs/best-practices"),
  typescriptUnions: source("Unions and Narrowing — TypeScript", "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions"),
  semver: source("Semantic Versioning", "https://semver.org/"),
  tanstackDefaults: source("Important Defaults — TanStack Query", "https://tanstack.com/query/latest/docs/framework/react/guides/important-defaults"),
  tanstackOptimistic: source("Optimistic Updates — TanStack Query", "https://tanstack.com/query/latest/docs/framework/react/guides/optimistic-updates"),
  reactRouter: source("React Router: Picking a Mode", "https://reactrouter.com/start/modes"),
  owaspXss: source("XSS Prevention — OWASP", "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"),
  owaspCsrf: source("CSRF Prevention — OWASP", "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"),
  owaspThreat: source("Threat Modeling — OWASP", "https://owasp.org/www-community/Threat_Modeling"),
  owaspOauth: source("OAuth 2.0 Cheat Sheet — OWASP", "https://cheatsheetseries.owasp.org/cheatsheets/OAuth2_Cheat_Sheet.html"),
  owaspCsp: source("Content Security Policy — OWASP", "https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html"),
  webVitals: source("Web Vitals — web.dev", "https://web.dev/articles/vitals"),
  webRender: source("Rendering performance — web.dev", "https://web.dev/articles/rendering-performance"),
  chromeMemory: source("Memory problems — Chrome DevTools", "https://developer.chrome.com/docs/devtools/memory-problems"),
  chromePerformance: source("Performance panel — Chrome DevTools", "https://developer.chrome.com/docs/devtools/performance"),
  githubActions: source("GitHub Actions documentation", "https://docs.github.com/en/actions"),
  sreIncident: source("Incident Response — Google SRE", "https://sre.google/workbook/incident-response/"),
  srePostmortem: source("Postmortem Culture — Google SRE", "https://sre.google/sre-book/postmortem-culture/"),
  openTelemetry: source("OpenTelemetry for the browser", "https://opentelemetry.io/docs/languages/js/getting-started/browser/"),
  adr: source("Architecture Decision Records", "https://adr.github.io/"),
  nodePackages: source("Package entry points — Node.js", "https://nodejs.org/api/packages.html#package-entry-points"),
  tsProjectReferences: source("Project References — TypeScript", "https://www.typescriptlang.org/docs/handbook/project-references.html"),
  featureToggles: source("Feature Toggles", "https://martinfowler.com/articles/feature-toggles.html"),
  parallelChange: source("Parallel Change", "https://martinfowler.com/bliki/ParallelChange.html"),
};

const KEYS_BY_NODE = {
  js_basics: ["mdnClosures", "mdnPromises"],
  react_mental_model: ["reactThinking", "reactRenderCommit"],
  components_props: ["reactProps", "reactThinking"],
  jsx_rendering: ["reactJsx"],
  events_propagation: ["reactEvents"],
  state_updates: ["reactSnapshot", "reactBatching"],
  hooks_rules: ["reactHooksRules", "reactUse"],
  custom_hooks: ["reactCustomHooks"],
  use_state_reducer: ["reactReducer"],
  forms_controlled: ["reactSharingState", "mdnForms"],
  form_validation: ["mdnForms"],
  lifting_state: ["reactSharingState"],
  derived_state: ["reactStateShape"],
  context: ["reactStateShape"],
  refs_dom: ["reactRefs"],
  effects: ["reactEffects"],
  effect_dependencies: ["reactEffectLifecycle", "reactEffectDependencies"],
  data_fetching: ["reactUseEffect", "mdnAbort"],
  async_race: ["mdnAbort"],
  routing: ["reactRouter", "mdnHistory"],
  auth_frontend: ["owaspOauth", "owaspCsrf"],
  server_state: ["tanstackDefaults"],
  react_query: ["tanstackDefaults"],
  optimistic_ui: ["tanstackOptimistic"],
  render_reconciliation: ["reactRenderCommit", "reactIdentity"],
  transitions_concurrency: ["reactTransitions"],
  keys_lists: ["reactKeys", "reactIdentity"],
  memoization: ["reactMemo", "reactUseMemo"],
  react_compiler: ["reactCompiler"],
  performance: ["reactProfiler", "chromePerformance", "webVitals"],
  suspense_lazy: ["reactLazy", "reactSuspense"],
  error_boundaries: ["reactBoundary"],
  accessibility: ["waiPatterns"],
  portals_dialogs: ["reactPortal", "waiPatterns"],
  styling_assets: ["mdnCssProperties", "wcagReflow"],
  component_architecture: ["reactThinking", "reactStateShape"],
  component_api_patterns: ["reactProps", "reactSharingState"],
  state_management: ["reactStateShape"],
  external_stores: ["reactUseEffect"],
  typescript_react: ["reactTypes", "typescriptUnions"],
  testing_rtl: ["testingLibrary", "testingUserEvent"],
  testing_async: ["msw", "testingLibrary"],
  security_frontend: ["owaspXss", "owaspCsrf", "mdnTrustedTypes"],
  ssr_hydration: ["reactHydration"],
  server_components: ["reactRsc", "reactSecurityRsc"],
  native_component_contract: ["mdnButton", "mdnForms"],
  public_component_contract: ["reactProps", "semver"],
  callback_contracts: ["reactEvents"],
  controlled_uncontrolled_api: ["reactSharingState"],
  draft_commit_state: ["reactStateShape"],
  library_type_design: ["reactTypes", "typescriptUnions"],
  api_evolution: ["semver"],
  behavior_ownership: ["mdnButton", "waiPatterns"],
  accessible_composites: ["waiPatterns", "waiCombobox"],
  design_tokens: ["mdnCssProperties"],
  resilient_ui: ["wcagReflow", "mdnIntl"],
  vendor_boundaries: ["semver"],
  proof_strategy: ["testingLibrary", "playwright"],
  scope_reviewability: ["semver"],
  case_design_system_select: ["waiCombobox", "mdnForms"],
  deployment_web: ["mdnHttpCache", "webVitals"],
  frontend_system_design: ["reactThinking", "owaspThreat", "webVitals"],
  module_boundaries_monorepo: ["nodePackages", "tsProjectReferences", "semver"],
  feature_flags_migrations: ["featureToggles", "parallelChange"],
  event_loop_tasks: ["mdnEventLoop"],
  browser_rendering_pipeline: ["webRender", "chromePerformance"],
  memory_resource_lifecycle: ["chromeMemory"],
  http_cache_network: ["mdnHttpCache"],
  realtime_offline: ["mdnWebSocket", "mdnOnline"],
  frontend_observability: ["webVitals", "openTelemetry"],
  ci_cd_release_strategy: ["githubActions"],
  incident_debugging: ["sreIncident", "srePostmortem"],
  threat_modeling_frontend: ["owaspThreat"],
  oauth_oidc_sessions: ["owaspOauth"],
  csp_supply_chain: ["owaspCsp"],
  testing_strategy: ["testingLibrary", "playwright"],
  contract_visual_e2e: ["playwright"],
  test_reliability: ["playwright"],
  product_metrics_experiments: ["webVitals"],
  i18n_content_resilience: ["mdnIntl", "wcagReflow"],
  ux_performance_tradeoffs: ["webVitals", "wcagReflow"],
  technical_direction: ["adr"],
  adr_rfc_decisions: ["adr"],
  code_review_mentoring: ["semver"],
  planning_delegation: ["sreIncident"],
  conflict_stakeholders: ["adr"],
};

export function getSupplementalReactSources(nodeId) {
  return (KEYS_BY_NODE[nodeId] ?? []).map((key) => SOURCES[key]);
}

export const REACT_REVIEW_NOTES = {
  hooks_rules: [
    "use es la excepción documentada a la regla de orden: puede llamarse dentro de condiciones y loops, pero sigue teniendo que ejecutarse durante render dentro de un componente o custom Hook. No debe envolverse en try/catch; Suspense y Error Boundaries modelan sus resultados.",
  ],
  server_components: [
    "Los Server Functions y el protocolo de Server Components son una superficie remota: tratá toda entrada como no confiable, autorizá cada operación y mantené el framework actualizado. React publicó correcciones de seguridad para implementaciones RSC a fines de 2025.",
  ],
  react_compiler: [
    "React Compiler 1.0 es estable y opcional. Puede adoptarse gradualmente; la documentación recomienda conservar memoización manual existente o retirarla con medición porque quitarla puede cambiar el resultado de compilación.",
  ],
  react_resources_activity: [
    "A diferencia de la mayoría de los Hooks, use puede llamarse dentro de condiciones y loops, pero debe seguir ejecutándose durante render dentro de un componente o Hook. Una Promise creada en cada render puede causar suspensión repetida; la fuente debe ser estable o venir del framework.",
  ],
};
