export const REACT_MILESTONES = [
  { id: "react_foundations", label: "Fundamentos", description: "Predecís cómo React transforma estado y props en UI.", color: "#61DAFB", nodeIds: ["js_basics", "react_mental_model", "components_props", "jsx_rendering", "react_values_elements", "events_propagation", "legacy_react_apis"] },
  { id: "react_state", label: "Estado y formularios", description: "Elegís fuente de verdad y modelás interacción local.", color: "#F59E0B", nodeIds: ["state_updates", "hooks_rules", "custom_hooks", "use_state_reducer", "forms_controlled", "form_validation", "lifting_state", "derived_state", "context", "refs_dom", "useid_identity"] },
  { id: "react_effects", label: "Efectos y datos", description: "Conectás la UI con red, cleanup, cancelación y retries.", color: "#A78BFA", nodeIds: ["effects", "effect_dependencies", "effect_timing_strict_mode", "data_fetching", "async_race"] },
  { id: "react_architecture", label: "Arquitectura de aplicación", description: "Diseñás rutas, auth, server state y límites de componentes.", color: "#2DD4BF", nodeIds: ["routing", "routing_data_apis", "auth_frontend", "server_state", "react_query", "optimistic_ui", "react_actions", "component_architecture", "component_api_patterns", "react_patterns_history", "state_management", "external_stores", "typescript_react"] },
  { id: "react_rendering", label: "Render y performance", description: "Entendés reconciliation y optimizás con evidencia.", color: "#4ADE80", nodeIds: ["render_reconciliation", "transitions_concurrency", "keys_lists", "memoization", "react_compiler", "performance", "suspense_lazy", "react_resources_activity", "error_boundaries"] },
  { id: "react_quality", label: "Testing y calidad", description: "Probás comportamiento real, async y errores del usuario.", color: "#F472B6", nodeIds: ["testing_rtl", "testing_async", "testing_tools_legacy"] },
  { id: "react_platform", label: "Web y producción", description: "Conectás React con accesibilidad, seguridad, SSR y deploy.", color: "#94A3B8", nodeIds: ["accessibility", "portals_dialogs", "styling_assets", "responsive_browser_subscriptions", "i18n_localization", "security_frontend", "ssr_hydration", "rendering_strategies", "server_components", "deployment_web"] },
  { id: "react_cases", label: "Casos de entrevista", description: "Podés diseñar dashboard, login y checkout desde el flujo de UI.", color: "#38BDF8", nodeIds: ["case_dashboard", "case_auth", "case_checkout"] },
  { id: "react_design_system", label: "Design system", description: "Diseñás componentes públicos con contratos y evidencia.", color: "#FB7185", nodeIds: ["native_component_contract", "public_component_contract", "callback_contracts", "controlled_uncontrolled_api", "draft_commit_state", "library_type_design", "api_evolution", "behavior_ownership", "accessible_composites", "design_tokens", "resilient_ui", "vendor_boundaries", "proof_strategy", "scope_reviewability", "case_design_system_select"] },
  { id: "react_runtime", label: "Browser y runtime", description: "Diagnosticás scheduling, pixels, red, memoria y conectividad.", color: "#FBBF24", nodeIds: ["event_loop_tasks", "browser_rendering_pipeline", "memory_resource_lifecycle", "http_cache_network", "realtime_offline"] },
  { id: "react_system_design", label: "Frontend system design", description: "Convertís requisitos ambiguos en límites y migraciones.", color: "#14B8A6", nodeIds: ["frontend_system_design", "module_boundaries_monorepo", "feature_flags_migrations"] },
  { id: "react_production", label: "Producción y reliability", description: "Desplegás, observás y respondés incidentes con control.", color: "#F97316", nodeIds: ["frontend_observability", "ci_cd_release_strategy", "incident_debugging"] },
  { id: "react_security_advanced", label: "Seguridad avanzada", description: "Modelás amenazas, identidad y defensa en profundidad.", color: "#EF4444", nodeIds: ["threat_modeling_frontend", "oauth_oidc_sessions", "csp_supply_chain"] },
  { id: "react_quality_strategy", label: "Estrategia de calidad", description: "Diseñás una suite confiable según riesgos reales.", color: "#EC4899", nodeIds: ["testing_strategy", "contract_visual_e2e", "test_reliability"] },
  { id: "react_product", label: "Producto y experiencia", description: "Conectás UX, contenido, métricas y performance.", color: "#A78BFA", nodeIds: ["product_metrics_experiments", "i18n_content_resilience", "ux_performance_tradeoffs"] },
  { id: "react_leadership", label: "Liderazgo técnico", description: "Escalás decisiones, ownership y crecimiento del equipo.", color: "#C084FC", nodeIds: ["technical_direction", "adr_rfc_decisions", "code_review_mentoring", "planning_delegation", "conflict_stakeholders"] },
];

export const REACT_SENIORITY_BANDS = [
  { id: "react_professional", stage: "NIVEL I", label: "React profesional", description: "Modelo mental, estado, asincronía, render y testing para entregar features con autonomía.", color: "#61DAFB", position: { x: 0.18, y: 0.48 }, milestoneIds: ["react_foundations", "react_state", "react_effects", "react_rendering", "react_quality"], requires: [] },
  { id: "senior_frontend", stage: "NIVEL II", label: "Senior frontend", description: "Arquitectura, browser, producción, seguridad y producto bajo restricciones reales.", color: "#F59E0B", position: { x: 0.52, y: 0.48 }, milestoneIds: ["react_architecture", "react_runtime", "react_system_design", "react_production", "react_platform", "react_security_advanced", "react_quality_strategy", "react_cases", "react_product"], requires: ["react_professional"] },
  { id: "senior_design_systems", stage: "ESPECIALIZACIÓN", label: "Senior Design Systems", description: "Contratos públicos, plataforma, accesibilidad y evolución de una librería compartida.", color: "#FB7185", position: { x: 0.78, y: 0.72 }, milestoneIds: ["react_design_system"], requires: ["react_professional"] },
  { id: "frontend_lead", stage: "NIVEL III", label: "Frontend Lead", description: "Dirección técnica, decisiones, mentoring, delegación y alineación con stakeholders.", color: "#C084FC", position: { x: 0.83, y: 0.24 }, milestoneIds: ["react_leadership"], requires: ["senior_frontend"] },
].map((band) => ({
  ...band,
  nodeIds: [...new Set(REACT_MILESTONES.filter((milestone) => band.milestoneIds.includes(milestone.id)).flatMap((milestone) => milestone.nodeIds))],
}));
