export const SENIOR_CATEGORIES = {
  runtime: { label: "Browser & runtime", color: "#FBBF24" },
  operations: { label: "Producción & reliability", color: "#F97316" },
  leadership: { label: "Producto & liderazgo", color: "#C084FC" },
};

export const SENIOR_CATEGORY_CONTEXT = {
  runtime: "Esta rama baja de React al browser: tareas, render visual, red y recursos que pueden sobrevivir más de lo esperado.",
  operations: "Una aplicación ya desplegada necesita evidencia, releases seguros y una forma disciplinada de responder cuando algo falla.",
  leadership: "El último nivel cambia el alcance: además de resolver código, hay que orientar decisiones, personas y resultados de producto.",
};

export const SENIOR_DATA = [
  ["event_loop_tasks", "Event loop, tasks y microtasks", "runtime"],
  ["browser_rendering_pipeline", "Rendering pipeline del browser", "runtime"],
  ["memory_resource_lifecycle", "Memoria, recursos y leaks", "runtime"],
  ["http_cache_network", "HTTP, caché y entrega de assets", "runtime"],
  ["realtime_offline", "Tiempo real, reconexión y offline", "runtime"],
  ["frontend_system_design", "Frontend system design", "architecture"],
  ["module_boundaries_monorepo", "Módulos, paquetes y monorepo", "architecture"],
  ["feature_flags_migrations", "Feature flags y migraciones graduales", "architecture"],
  ["frontend_observability", "Observabilidad frontend", "operations"],
  ["ci_cd_release_strategy", "CI/CD y estrategia de releases", "operations"],
  ["incident_debugging", "Incidentes y debugging en producción", "operations"],
  ["threat_modeling_frontend", "Threat modeling frontend", "platform"],
  ["oauth_oidc_sessions", "OAuth, OIDC y sesiones", "platform"],
  ["csp_supply_chain", "CSP y supply-chain security", "platform"],
  ["testing_strategy", "Estrategia de testing", "quality"],
  ["contract_visual_e2e", "Contract, visual y E2E tests", "quality"],
  ["test_reliability", "Flakiness y confiabilidad de tests", "quality"],
  ["product_metrics_experiments", "Métricas, analytics y experimentos", "leadership"],
  ["i18n_content_resilience", "i18n y contenido resiliente", "leadership"],
  ["ux_performance_tradeoffs", "Trade-offs de UX y performance", "leadership"],
  ["technical_direction", "Dirección técnica y principios", "leadership"],
  ["adr_rfc_decisions", "ADRs, RFCs y decisiones reversibles", "leadership"],
  ["code_review_mentoring", "Code review y mentoring", "leadership"],
  ["planning_delegation", "Planificación y delegación", "leadership"],
  ["conflict_stakeholders", "Desacuerdos y stakeholders", "leadership"],
];

export const SENIOR_PRIORITY_ORDER = SENIOR_DATA.map(([id]) => id);

export const SENIOR_PREREQUISITES = {
  event_loop_tasks: ["js_basics", "effects"],
  browser_rendering_pipeline: ["event_loop_tasks", "performance"],
  memory_resource_lifecycle: ["effect_dependencies", "browser_rendering_pipeline"],
  http_cache_network: ["data_fetching", "deployment_web"],
  realtime_offline: ["async_race", "http_cache_network"],
  frontend_system_design: ["component_architecture", "state_management", "server_state"],
  module_boundaries_monorepo: ["frontend_system_design", "typescript_react"],
  feature_flags_migrations: ["frontend_system_design", "testing_async"],
  frontend_observability: ["deployment_web", "error_boundaries", "performance"],
  ci_cd_release_strategy: ["deployment_web", "testing_async"],
  incident_debugging: ["frontend_observability", "browser_rendering_pipeline"],
  threat_modeling_frontend: ["security_frontend", "auth_frontend"],
  oauth_oidc_sessions: ["threat_modeling_frontend"],
  csp_supply_chain: ["threat_modeling_frontend", "deployment_web"],
  testing_strategy: ["testing_rtl", "testing_async"],
  contract_visual_e2e: ["testing_strategy", "accessibility", "styling_assets"],
  test_reliability: ["testing_strategy", "ci_cd_release_strategy"],
  product_metrics_experiments: ["case_dashboard", "frontend_observability"],
  i18n_content_resilience: ["accessibility", "styling_assets"],
  ux_performance_tradeoffs: ["performance", "accessibility", "product_metrics_experiments"],
  technical_direction: ["frontend_system_design", "incident_debugging", "ux_performance_tradeoffs"],
  adr_rfc_decisions: ["technical_direction", "module_boundaries_monorepo"],
  code_review_mentoring: ["testing_strategy", "scope_reviewability"],
  planning_delegation: ["technical_direction", "ci_cd_release_strategy"],
  conflict_stakeholders: ["planning_delegation", "product_metrics_experiments"],
};

const details = (level, summary, why, code, codeLabel, steps, pitfalls, takeaway, explanation, related = []) => [
  level,
  summary,
  why,
  code,
  codeLabel,
  steps,
  pitfalls,
  takeaway,
  { explanation, related },
];

export const SENIOR_TOPIC_DETAILS = {
  event_loop_tasks: details(
    "Browser runtime",
    "El event loop decide cuándo puede ejecutarse JavaScript y en qué orden se procesan tasks, microtasks, rendering y callbacks.",
    "Permite explicar UIs congeladas, promesas que corren antes que timers y por qué dividir trabajo largo mejora la interacción.",
    "console.log('A')\\nsetTimeout(() => console.log('task'), 0)\\nPromise.resolve().then(() => console.log('microtask'))\\nconsole.log('B')\\n// A, B, microtask, task",
    "Orden observable del event loop",
    ["Una task ejecuta JavaScript hasta devolver el control.", "Al terminar, el browser vacía microtasks antes de la siguiente task.", "El rendering ocurre cuando el browser recupera una oportunidad para pintar.", "Trabajo CPU largo debe dividirse o moverse fuera del hilo principal."],
    ["Una cadena infinita de microtasks también puede impedir que el browser pinte.", "setTimeout(0) no significa ejecución inmediata.", "React scheduling opera sobre estas restricciones; no elimina el costo del JavaScript."],
    "Si el hilo principal no vuelve al browser, no hay input responsivo ni nuevo frame.",
    "Pensalo como una cola compartida por tu aplicación y la plataforma. Cada callback que monopoliza esa cola retrasa eventos, layout y paint; por eso la solución depende de si el costo es CPU, red o coordinación.",
    ["effects", "transitions_concurrency"]
  ),
  browser_rendering_pipeline: details(
    "Browser runtime",
    "El browser convierte DOM y CSS en style, layout, paint y composición; cada etapa tiene costos y disparadores diferentes.",
    "Un senior debe distinguir un render React costoso de layout thrashing, imágenes pesadas o demasiada pintura.",
    "performance.mark('before')\\nconst rect = element.getBoundingClientRect() // read layout\\nelement.style.transform = `translateX(${rect.width}px)`\\nperformance.mark('after')",
    "Medir antes de cambiar",
    ["Style resuelve reglas CSS.", "Layout calcula geometría.", "Paint dibuja pixels y layers.", "Composición combina layers; transform y opacity suelen evitar nuevo layout."],
    ["Alternar lecturas y escrituras de layout puede forzar cálculos sincrónicos repetidos.", "will-change permanente consume memoria.", "Reducir renders React no arregla una imagen enorme ni un selector CSS problemático."],
    "Encontrá qué etapa consume el frame antes de elegir la optimización.",
    "React decide qué DOM necesita cambiar; el browser decide cómo convertir ese DOM en pixels. DevTools Performance permite ver si la demora está en scripting, layout, paint o composición.",
    ["performance", "styling_assets"]
  ),
  memory_resource_lifecycle: details(
    "Browser runtime",
    "Un leak aparece cuando listeners, timers, observers, caches o closures mantienen referencias que ya no deberían seguir vivas.",
    "Las SPAs pueden permanecer abiertas horas; una fuga pequeña por navegación se convierte en degradación real.",
    "useEffect(() => {\\n  const observer = new ResizeObserver(handleResize)\\n  observer.observe(node)\\n  return () => observer.disconnect()\\n}, [node])",
    "Adquirir y liberar el recurso",
    ["Nombrá el recurso creado.", "Definí quién es su owner.", "Liberalo en cleanup o cuando termina su vida útil.", "Confirmá con heap snapshots y allocation profiling, no solo mirando RAM total."],
    ["Guardar nodos DOM en una cache global puede retener subárboles enteros.", "Un cleanup incorrecto que usa otro callback no remueve el listener original.", "Abortar fetch evita trabajo obsoleto aunque el garbage collector pudiera recuperar memoria."],
    "Todo recurso necesita owner, duración y mecanismo de liberación.",
    "State desmontado no es el único riesgo. Observers, subscriptions y estructuras globales pueden seguir apuntando a objetos viejos; la prueba es que las referencias desaparezcan después de repetir el flujo.",
    ["effect_dependencies", "portals_dialogs"]
  ),
  http_cache_network: details(
    "Browser runtime",
    "Performance de red depende de HTTP, compresión, caché, CDN, prioridad y del tamaño/orden de los recursos.",
    "Permite diseñar assets inmutables, datos revalidables y diagnósticos basados en waterfall en lugar de intuición.",
    "Cache-Control: public, max-age=31536000, immutable\\n/app.a83f1.js\\n\\nCache-Control: no-cache\\n/index.html",
    "Políticas distintas por recurso",
    ["Assets fingerprinted pueden cachearse por largo tiempo.", "HTML suele revalidarse para descubrir la nueva versión.", "ETag permite 304 sin volver a transferir el body.", "El waterfall revela DNS, conexión, TTFB, descarga y dependencias bloqueantes."],
    ["no-cache no significa no almacenar; significa revalidar.", "Cachear index.html como inmutable puede dejar una app apuntando a chunks eliminados.", "Más requests no siempre es peor bajo HTTP/2; medí tamaño y dependencia crítica."],
    "La estrategia de cache es parte del protocolo de deploy.",
    "Separá contenido versionado de respuestas que representan estado cambiante. El browser, CDN y servidor participan en la frescura; React Query no reemplaza la caché HTTP.",
    ["deployment_web", "data_fetching"]
  ),
  realtime_offline: details(
    "Browser runtime",
    "Tiempo real y offline requieren modelar conexión, reconexión, orden, duplicados y reconciliación con la autoridad del servidor.",
    "Una conexión abierta no garantiza consistencia; los mensajes pueden repetirse, faltar o llegar después de un refetch.",
    "socket.onmessage = event => {\\n  const message = parse(event.data)\\n  if (!seen.has(message.id)) apply(message)\\n}\\n// reconnect -> refetch snapshot -> resume stream",
    "Snapshot más eventos",
    ["Obtené un snapshot autoritativo.", "Aplicá eventos identificables y deduplicables.", "Reconectá con backoff y jitter.", "Al recuperar conexión, reconciliá antes de asumir continuidad."],
    ["Reintentar inmediatamente desde cientos de clientes produce thundering herd.", "Guardar mutaciones offline exige resolver conflictos.", "El indicador online del browser no prueba que tu API sea alcanzable."],
    "Tiempo real es un problema de consistencia y recuperación, no solo de sockets.",
    "Diseñá explícitamente qué ve el usuario cuando la conexión cae y qué dato vuelve a ser autoridad al reconectar. SSE, WebSocket o polling son transportes; la semántica vive encima.",
    ["async_race", "optimistic_ui"]
  ),
  frontend_system_design: details(
    "System design",
    "Frontend system design transforma requisitos en límites de dominio, flujos de datos, estados de fallo y contratos entre browser, API y equipos.",
    "Es la habilidad central para responder consignas abiertas sin saltar directamente a componentes o librerías.",
    "Requisitos -> invariantes -> flujos -> ownership\\n          -> límites -> fallas -> evidencia\\n\\nOrders feature:\\nURL -> query cache -> screen -> mutation -> invalidation",
    "Del requisito a una arquitectura",
    ["Aclarar usuarios, escala y restricciones.", "Nombrar estados e invariantes.", "Asignar ownership a URL, componente, store, cache y backend.", "Dibujar límites, fallas, observabilidad y estrategia de evolución."],
    ["Un diagrama de cajas sin flujo no explica el sistema.", "Elegir Redux, microfrontends o SSR antes del problema es solution-first.", "El happy path no alcanza: incluí permisos, errores, retries y estados parciales."],
    "Una arquitectura buena hace visibles decisiones, ownership y recuperación.",
    "El resultado no es la mayor cantidad de capas. Es una explicación verificable de quién sabe qué, cómo cambia el dato, dónde puede fallar y cómo se reemplaza una pieza sin rehacer todo.",
    ["component_architecture", "case_dashboard"]
  ),
  module_boundaries_monorepo: details(
    "System design",
    "Los límites de módulos definen qué puede importar cada feature, qué contratos son públicos y quién puede cambiar una dependencia.",
    "En una base grande, la dirección de dependencias afecta más la mantenibilidad que la estructura exacta de carpetas.",
    "features/orders -> domain/order -> shared/http\\nfeatures/orders -X-> features/billing/internal\\n\\npackages/ui exports public entry points",
    "Dirección explícita de dependencias",
    ["Agrupá por capacidad de negocio.", "Exponé entry points públicos.", "Evitá imports profundos de internals.", "Usá tooling para detectar ciclos y ownership para revisar fronteras sensibles."],
    ["Un monorepo no crea modularidad por sí solo.", "shared puede convertirse en un cajón sin owner.", "Separar paquetes prematuramente agrega versionado y builds sin aislar una decisión real."],
    "Una frontera vale cuando reduce acoplamiento y hace el cambio local.",
    "Paquete, carpeta y equipo son herramientas distintas. Diseñá primero el contrato y la dirección de dependencia; después elegí si necesita aislamiento de build, ownership o publicación.",
    ["component_architecture", "vendor_boundaries"]
  ),
  feature_flags_migrations: details(
    "System design",
    "Una migración gradual permite cambiar arquitectura o UX manteniendo el sistema desplegable y reversible en cada etapa.",
    "Los proyectos senior rara vez pueden detener todo para reemplazar una aplicación completa.",
    "if (flags.newCheckout) return <NewCheckout />\\nreturn <LegacyCheckout />\\n\\n// expand -> migrate -> contract -> remove",
    "Cambio reversible",
    ["Definí población y criterio de éxito.", "Separá deploy de release.", "Instrumentá ambos caminos.", "Retirá flag, código viejo y métricas temporales cuando termina la migración."],
    ["Flags permanentes duplican estados y deuda.", "Dos implementaciones escribiendo formatos incompatibles requieren estrategia de datos.", "Un rollback de UI no ayuda si ya hubo una migración destructiva de backend."],
    "Cada fase debe poder desplegarse, observarse y revertirse.",
    "Usá patrones como strangler o expand/contract para mantener compatibilidad mientras cambia el consumidor. La migración incluye datos, contratos, telemetría y limpieza final.",
    ["api_evolution", "deployment_web"]
  ),
  frontend_observability: details(
    "Producción",
    "Observabilidad conecta errores, performance y acciones del usuario con versión, ruta, dispositivo y estado relevante.",
    "Sin contexto, un stack trace minificado o un promedio global difícilmente permite reproducir un problema real.",
    "captureError(error, {\\n  release, route, feature, correlationId,\\n  user: anonymizedUser\\n})",
    "Evento accionable",
    ["Versioná source maps de forma privada.", "Correlacioná frontend y backend.", "Medí Web Vitals y operaciones de negocio.", "Definí alertas por impacto y un owner que pueda actuar."],
    ["Registrar datos personales o tokens crea otro incidente.", "Un promedio oculta dispositivos o percentiles lentos.", "Más logs sin estructura aumentan costo, no comprensión."],
    "Una señal sirve si conduce desde impacto hasta causa probable.",
    "Combiná telemetry técnica con el flujo del usuario: qué intentaba hacer, qué release ejecutaba y qué dependencia respondió. Observabilidad no es instalar un SDK; es diseñar preguntas que producción pueda contestar.",
    ["deployment_web", "performance"]
  ),
  ci_cd_release_strategy: details(
    "Producción",
    "CI/CD convierte un cambio en un artefacto verificable y lo libera con controles proporcionales al riesgo.",
    "Un lead debe equilibrar velocidad, confianza y capacidad de rollback.",
    "lint -> types -> unit/integration -> build\\n      -> preview -> canary -> production\\n      -> monitor -> promote | rollback",
    "Pipeline con promoción",
    ["Generá un artefacto reproducible.", "Ejecutá checks baratos antes que suites costosas.", "Probá el artefacto que será desplegado.", "Liberá gradualmente y monitoreá señales de éxito y error."],
    ["Rebuild por ambiente puede producir artefactos distintos.", "Una pipeline lenta incentiva saltarse controles.", "Rollback debe considerar compatibilidad con APIs y datos ya modificados."],
    "Release seguro significa detectar, limitar y revertir impacto.",
    "No todos los cambios necesitan el mismo gate. Usá riesgo, blast radius y observabilidad para elegir preview, canary, aprobación o despliegue directo.",
    ["deployment_web", "testing_async"]
  ),
  incident_debugging: details(
    "Producción",
    "Responder un incidente exige estabilizar primero, construir una timeline con evidencia y corregir la causa sin perder aprendizaje.",
    "La calidad senior aparece cuando hay presión, información incompleta y usuarios afectados.",
    "1. confirmar impacto y owner\\n2. mitigar: flag o rollback\\n3. correlacionar release + señales\\n4. reproducir y corregir\\n5. postmortem sin culpa",
    "Flujo de incidente",
    ["Declarar severidad y canal.", "Detener el daño con la acción más reversible.", "Preservar evidencia.", "Comunicar estado y próximos checkpoints.", "Convertir la causa en acciones sistémicas con owner."],
    ["Debuggear durante horas antes de mitigar prolonga impacto.", "Cambiar varias variables simultáneamente destruye evidencia.", "Un postmortem que culpa a una persona no mejora el sistema."],
    "Primero restaurá servicio; después entendé y fortalecé el sistema.",
    "Un buen diagnóstico formula hipótesis y busca señales que podrían refutarlas. El objetivo final no es solo el fix: es reducir la probabilidad o el impacto de la próxima falla.",
    ["frontend_observability", "feature_flags_migrations"]
  ),
  threat_modeling_frontend: details(
    "Seguridad",
    "Threat modeling identifica activos, fronteras de confianza, atacantes posibles y mitigaciones antes de implementar.",
    "Ayuda a priorizar riesgos reales en lugar de aplicar una checklist sin contexto.",
    "Activo: sesión del usuario\\nFronteras: browser <-> CDN <-> API <-> IdP\\nAmenazas: XSS, token theft, redirect abuse\\nMitigaciones: CSP, HttpOnly, allowlist, rotación",
    "Modelo de amenazas pequeño",
    ["Enumerá activos y datos sensibles.", "Dibujá entradas y fronteras.", "Preguntá cómo se falsifica, altera, filtra o interrumpe cada flujo.", "Elegí mitigaciones y riesgo residual."],
    ["Ocultar botones no es autorización.", "Confiar en que el input nació en tu UI ignora clientes modificados.", "Agregar controles sin owner ni monitoreo produce seguridad nominal."],
    "Protegé activos concretos en fronteras concretas.",
    "El frontend es una frontera hostil porque el usuario controla el runtime. La UI puede reducir exposición y proteger sesión, pero la API debe validar identidad, permiso e integridad.",
    ["security_frontend", "auth_frontend"]
  ),
  oauth_oidc_sessions: details(
    "Seguridad",
    "OAuth delega autorización; OpenID Connect agrega identidad. En una app web moderna, Authorization Code con PKCE evita entregar credenciales al frontend.",
    "Permite diseñar login federado sin confundir access token, ID token, refresh token y sesión de aplicación.",
    "React -> IdP: authorize + code_challenge\\nIdP -> callback: authorization code\\nBackend/BFF -> IdP: code + verifier\\nBackend -> browser: session HttpOnly",
    "Authorization Code + PKCE",
    ["state protege el retorno contra requests forjadas.", "PKCE vincula el código con quien inició el flujo.", "El ID token describe autenticación; el access token autoriza una API.", "Una sesión HttpOnly/BFF reduce exposición de tokens al JavaScript."],
    ["Usar ID token como access token mezcla audiencias.", "Guardar refresh tokens largos en localStorage aumenta impacto de XSS.", "Redirect URIs abiertas permiten desviar códigos."],
    "Identidad, autorización y sesión son contratos distintos.",
    "Primero decidí quién consume el token y qué arquitectura de sesión necesita tu app. Después elegí dónde persiste cada credencial y cómo se rota, revoca y expira.",
    ["auth_frontend", "case_auth"]
  ),
  csp_supply_chain: details(
    "Seguridad",
    "CSP limita qué código y recursos puede ejecutar una página; supply-chain security reduce la confianza implícita en dependencias y builds.",
    "XSS y paquetes comprometidos pueden ejecutar código con los permisos de tu aplicación.",
    "Content-Security-Policy:\\n  default-src 'self';\\n  script-src 'self' 'nonce-<random>';\\n  object-src 'none'; base-uri 'self'",
    "Defensa en profundidad",
    ["Desplegá CSP primero en report-only.", "Eliminá inline scripts o usá nonces.", "Bloqueá versiones y revisá provenance/licencias.", "Escaneá dependencias sin actualizar ciegamente cambios breaking."],
    ["unsafe-inline debilita la protección principal.", "Un lockfile reduce variación, no prueba que el paquete sea confiable.", "Subir source maps públicos puede revelar implementación y rutas internas."],
    "Reducí qué código puede entrar y qué código puede ejecutarse.",
    "CSP no reemplaza sanitización y un scanner no reemplaza revisión. Ambas capas limitan blast radius cuando otra prevención falla.",
    ["security_frontend", "deployment_web"]
  ),
  testing_strategy: details(
    "Calidad",
    "Una estrategia de testing asigna cada riesgo al harness más barato que puede observarlo con fidelidad.",
    "Evita suites enormes que prueban detalles internos mientras dejan sin protección contratos críticos.",
    "Tipos: contratos estáticos\\nUnit: lógica pura\\nRTL: comportamiento de UI\\nContract: integración entre servicios\\nE2E: journeys críticos\\nVisual: regresión de estados",
    "Riesgo por capa",
    ["Listá comportamientos y fallas costosas.", "Elegí la capa con mejor señal/costo.", "Protegé pocos journeys E2E críticos.", "Medí flakiness, duración y defectos escapados."],
    ["La pirámide no prescribe porcentajes universales.", "Duplicar el mismo caso en todas las capas multiplica mantenimiento.", "Coverage de líneas no demuestra que un flujo funcione."],
    "La suite es un portafolio de confianza, no una competencia de cantidad.",
    "Empezá por la afirmación observable y preguntá qué entorno necesita. Un parser puede probarse sin React; foco real o navegación requieren browser; compatibilidad de API puede necesitar contract tests.",
    ["testing_rtl", "testing_async"]
  ),
  contract_visual_e2e: details(
    "Calidad",
    "Contract, visual y E2E tests protegen riesgos que un test unitario o jsdom no puede representar bien.",
    "Los límites entre servicios, el layout real y los journeys completos suelen fallar aunque cada unidad pase.",
    "Contract: schema request/response\\nVisual: themes + viewport + states\\nE2E: login -> checkout -> confirmation",
    "Pruebas complementarias",
    ["Contract tests verifican compatibilidad entre productor y consumidor.", "Visual regression captura geometría, tokens y estados.", "E2E valida integración desplegada y navegación real.", "Cada failure debe indicar qué contrato se perdió."],
    ["Snapshots visuales sin estados definidos generan ruido.", "E2E para cada edge case vuelve lenta y frágil la suite.", "Mockear toda la red en E2E puede ocultar el contrato que querías probar."],
    "Usá el entorno real solo para el riesgo que necesita realidad.",
    "Estas capas no reemplazan RTL; completan su punto ciego. Elegí casos estables y de alto valor: forms, auth, foco, overlays, compatibilidad de API y estados visuales públicos.",
    ["testing_strategy", "proof_strategy"]
  ),
  test_reliability: details(
    "Calidad",
    "Un test flaky alterna resultados sin cambio relevante y destruye confianza en la señal de CI.",
    "Cuando fallar deja de significar algo, el equipo reintenta o ignora la suite.",
    "await expect.poll(() => api.status()).toBe('ready')\\n// esperar una condición observable, no sleep(2000)",
    "Sincronización determinista",
    ["Clasificá causa: tiempo, datos, orden, ambiente o dependencia.", "Aislá estado y generá datos únicos.", "Esperá condiciones observables.", "Ponele owner y fecha a cualquier quarantine."],
    ["Aumentar timeouts solo hace más lenta una carrera.", "Retry automático puede ocultar una regresión real.", "Tests que dependen del orden comparten estado accidental."],
    "Una suite confiable falla por una razón reproducible.",
    "Tratala como producción: medí tasa de fallos, duración y casos inestables. El objetivo no es cero variabilidad mágica, sino detectar y eliminar fuentes no controladas.",
    ["testing_strategy", "ci_cd_release_strategy"]
  ),
  product_metrics_experiments: details(
    "Producto",
    "Métricas conectan decisiones de UI con resultados del usuario; experimentos prueban una hipótesis con exposición y guardrails explícitos.",
    "Un lead frontend debe evitar tanto decidir solo por intuición como optimizar una métrica dañando el producto.",
    "Hipótesis: simplificar checkout aumenta completion\\nPrimary: checkout_completed / checkout_started\\nGuardrails: errores, latencia, cancelaciones\\nSegmentos: device, locale, usuario nuevo",
    "Hipótesis medible",
    ["Definí evento semántico y owner.", "Validá calidad y pérdida de eventos.", "Elegí métrica primaria y guardrails.", "Interpretá segmentos y significancia junto con contexto cualitativo."],
    ["Page views no explican si el usuario cumplió su objetivo.", "Cambiar la definición del evento rompe comparaciones.", "Más conversión con más errores o manipulación puede ser peor producto."],
    "Medí resultados y efectos secundarios, no actividad por actividad.",
    "Analytics también es contrato: nombres, payload, privacidad y versión. Un experimento sano parte de una decisión que realmente cambiarías según el resultado.",
    ["case_dashboard", "frontend_observability"]
  ),
  i18n_content_resilience: details(
    "Producto",
    "Internacionalización cambia texto, dirección, formatos y espacio disponible; una UI resiliente preserva significado bajo esa variación.",
    "El copy real y el zoom suelen revelar assumptions que el mock en inglés no mostró.",
    "new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(date)\\n\\n.card { min-inline-size: 0; overflow-wrap: anywhere; }",
    "Contenido y layout variables",
    ["Usá Intl para fechas, números y pluralización.", "Diseñá con propiedades lógicas para RTL.", "Probá copy larga, vacía y scripts distintos.", "No construyas oraciones concatenando fragmentos traducidos."],
    ["Un ancho fijo puede cortar alemán o zoom 200%.", "Traducir aria-labels por separado puede desalinear nombre visible y accesible.", "Locale no debe decidir reglas de negocio."],
    "El contenido es input del layout, no decoración posterior.",
    "Pensá cada componente como un contenedor de texto no controlado por su autor. i18n, accesibilidad y responsive se encuentran en la misma pregunta: qué variación soporta el contrato.",
    ["resilient_ui", "accessibility"]
  ),
  ux_performance_tradeoffs: details(
    "Producto",
    "Una decisión senior equilibra velocidad percibida, accesibilidad, claridad, costo técnico y objetivo de negocio.",
    "La métrica más rápida o la animación más atractiva no necesariamente produce la mejor experiencia.",
    "Decisión: optimistic save\\nBeneficio: feedback inmediato\\nRiesgo: rollback confuso\\nGuardrails: error rate, undo, a11y announcements\\nFallback: pending explícito",
    "Trade-off documentado",
    ["Nombrá usuario y objetivo.", "Compará beneficio con failure modes.", "Incluí dispositivos, accesibilidad y contenido extremo.", "Definí evidencia y opción reversible."],
    ["Skeletons pueden hacer una pantalla parecer más lenta o provocar layout shift.", "Optimismo en pagos puede mentir sobre un resultado crítico.", "Una animación fluida que ignora reduced motion sigue siendo un defecto."],
    "La mejor solución optimiza el objetivo completo, no una métrica aislada.",
    "Explicá por qué el trade-off es adecuado para este flujo y qué señal te haría cambiarlo. Esa capacidad de revisión es más senior que defender una receta universal.",
    ["performance", "accessibility"]
  ),
  technical_direction: details(
    "Liderazgo",
    "Dirección técnica define pocos principios y límites que permiten a varios equipos tomar decisiones compatibles sin esperar permiso constante.",
    "El liderazgo escala mediante contexto y mecanismos, no convirtiéndose en cuello de botella.",
    "Principios:\\n1. URL posee estado navegable\\n2. API autoriza; UI no duplica policy\\n3. Features importan contratos públicos\\n4. Cambios críticos son observables y reversibles",
    "Principios accionables",
    ["Conectá dirección con objetivos de producto.", "Definí invariantes y decisiones delegables.", "Creá ejemplos, tooling y feedback loops.", "Revisá principios cuando la evidencia cambia."],
    ["Un documento aspiracional sin mecanismos no cambia el sistema.", "Estandarizar cada detalle reduce autonomía.", "El lead que aprueba todo impide que el equipo crezca."],
    "Dale al equipo contexto suficiente para decidir sin vos.",
    "La dirección útil reduce decisiones repetidas y hace visibles las excepciones. Se sostiene con arquitectura, docs, revisión, métricas y ownership distribuido.",
    ["frontend_system_design", "incident_debugging"]
  ),
  adr_rfc_decisions: details(
    "Liderazgo",
    "ADRs registran decisiones tomadas; RFCs permiten discutir cambios importantes antes de que su costo quede enterrado en código.",
    "Preservan contexto, alternativas y condiciones de revisión para que el equipo no repita debates o convierta decisiones temporales en dogma.",
    "Contexto -> fuerzas -> opciones\\nDecisión -> consecuencias\\nReversibilidad -> plan de migración\\nReview date -> señales para reconsiderar",
    "Documento de decisión",
    ["Ajustá profundidad al blast radius.", "Separá hechos, supuestos y preferencias.", "Incluí alternativas y por qué no ahora.", "Nombrá owner, rollout y criterio de revisión."],
    ["Un RFC de 30 páginas para una decisión local frena al equipo.", "Documentar solo la opción ganadora oculta el trade-off.", "ADR no reemplaza comunicación con afectados."],
    "Registrá el porqué y la condición de cambio, no una novela.",
    "Las decisiones reversibles necesitan velocidad; las irreversibles o transversales necesitan más evidencia. El formato sirve para calibrar esa inversión y construir memoria técnica.",
    ["technical_direction", "module_boundaries_monorepo"]
  ),
  code_review_mentoring: details(
    "Liderazgo",
    "Code review protege comportamiento y enseña modelos mentales; mentoring transfiere criterio hasta que otra persona puede tomar decisiones sola.",
    "Un lead se mide también por la calidad y autonomía que produce alrededor suyo.",
    "Review:\\n- riesgo observable\\n- evidencia y reproducción\\n- severidad e intención\\nMentoring:\\n- preguntar modelo mental\\n- mostrar frontera\\n- dejar decidir con guardrails",
    "Feedback que desarrolla criterio",
    ["Revisá contrato, ownership, plataforma, prueba y scope.", "Separá bug de preferencia.", "Explicá impacto y opción concreta.", "Ajustá ayuda al nivel: enseñar, acompañar o delegar."],
    ["Reescribir el código de otra persona no enseña.", "Comentarios vagos como 'esto está mal' no permiten actuar.", "Usar review para imponer gusto ralentiza y reduce seguridad psicológica."],
    "El mejor review mejora el cambio y el próximo cambio del autor.",
    "Pedí evidencia proporcional al riesgo y dejá clara la intención del comentario. En mentoring, el éxito es que la persona construya el modelo mental, no que copie tu solución.",
    ["scope_reviewability", "testing_strategy"]
  ),
  planning_delegation: details(
    "Liderazgo",
    "Planificar divide un resultado en incrementos verificables; delegar entrega contexto, autoridad y límites, no solo tareas.",
    "La entrega de equipo falla cuando dependencias, riesgos y decisiones quedan concentrados en una persona.",
    "Outcome -> milestones verticales -> owners\\n       -> dependencias -> riesgos -> checkpoints\\nDelegación: objetivo + constraints + decisión + señal de éxito",
    "Plan y ownership",
    ["Definí resultado y no solo output.", "Cortá verticalmente para obtener feedback temprano.", "Asigná owner y decisiones que puede tomar.", "Creá checkpoints por riesgo, no micro-management diario."],
    ["Repartir archivos no crea ownership.", "Estimaciones sin incertidumbre se convierten en promesas falsas.", "Delegar sin contexto obliga a adivinar o volver por cada decisión."],
    "Delegá decisiones con guardrails y mantené visible el riesgo.",
    "Un buen plan cambia cuando aprende. El lead protege el objetivo, hace explícitas dependencias y permite que el equipo ajuste implementación sin perder alineación.",
    ["technical_direction", "ci_cd_release_strategy"]
  ),
  conflict_stakeholders: details(
    "Liderazgo",
    "Los desacuerdos técnicos suelen mezclar objetivos, riesgos, evidencia y preferencias; liderar es hacer esas capas visibles y lograr una decisión sostenible.",
    "Producto, diseño, backend y frontend optimizan partes distintas del mismo sistema.",
    "Objetivo compartido: reducir abandono\\nRestricciones: fecha, a11y, API, riesgo\\nOpciones: A/B/C con trade-offs\\nDecisor + fecha + señal de revisión",
    "Desacuerdo convertido en decisión",
    ["Escuchá y reformulá la preocupación.", "Alineá objetivo y constraints.", "Compará opciones con evidencia.", "Definí quién decide y documentá el resultado.", "Disagree and commit sin borrar la posibilidad de revisar."],
    ["Ganar el argumento puede perder confianza y contexto.", "Escalar antes de intentar resolver localmente agrega política.", "Consenso total no es requisito para una decisión clara."],
    "Hacé que el desacuerdo produzca claridad, no ganadores y perdedores.",
    "La autoridad formal es el último recurso. Un lead efectivo traduce perspectivas, señala costos y mantiene la relación de trabajo después de decidir.",
    ["planning_delegation", "product_metrics_experiments"]
  ),
};
